# Translations template for pypilot.
# Copyright (C) 2021 ORGANIZATION
# This file is distributed under the same license as the pypilot project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2021.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: pypilot 0.32\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2021-09-18 00:31-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.6.0\n"

#: pypilot/autopilot.py:139
msgid "Available Pilots"
msgstr ""

#: pypilot/autopilot.py:161
msgid "warning: failed to open special file"
msgstr ""

#: pypilot/autopilot.py:161
msgid "for writing"
msgstr ""

#: pypilot/autopilot.py:162
msgid "cannot stroke the watchdog"
msgstr ""

#: pypilot/autopilot.py:166
msgid "warning: failed to make autopilot process realtime"
msgstr ""

#: pypilot/autopilot.py:337
msgid "server/client is running too _slowly_"
msgstr ""

#: pypilot/autopilot.py:343
msgid "sensors is running too _slowly_"
msgstr ""

#: pypilot/autopilot.py:420
msgid "autopilot routine is running too _slowly_"
msgstr ""

#: pypilot/autopilot.py:429
msgid "servo is running too _slowly_"
msgstr ""

#: pypilot/boatimu.py:33
msgid "RTIMU library not detected, please install it"
msgstr ""

#: pypilot/boatimu.py:56
msgid "Using settings file"
msgstr ""

#: pypilot/boatimu.py:96
msgid "ERROR: No IMU Detected"
msgstr ""

#: pypilot/boatimu.py:104
msgid "ERROR: IMU Init Failed, no inertial data available"
msgstr ""

#: pypilot/boatimu.py:126
msgid "warning, failed to make imu process realtime"
msgstr ""

#: pypilot/boatimu.py:128
msgid "made imu process realtime"
msgstr ""

#: pypilot/boatimu.py:140
msgid "setting initial gyro bias"
msgstr ""

#: pypilot/boatimu.py:156
msgid "imu process failed to keep time"
msgstr ""

#: pypilot/boatimu.py:164
msgid "failed to read IMU!"
msgstr ""

#: pypilot/boatimu.py:196
msgid "imu rate set to rate"
msgstr ""

#: pypilot/boatimu.py:210
msgid "too high standing gyro bias, resetting sensors"
msgstr ""

#: pypilot/boatimu.py:215
msgid "compass out of range, resetting"
msgstr ""

#: pypilot/boatimu.py:307
msgid "warning, failed to make calibration process other"
msgstr ""

#: pypilot/boatimu.py:309
msgid "warning, failed to make calibration process idle, trying renice"
msgstr ""

#: pypilot/boatimu.py:311
msgid "warning, failed to renice calibration process"
msgstr ""

#: pypilot/boatimu.py:318
msgid "calibration loaded, starting"
msgstr ""

#: pypilot/boatimu.py:322
msgid "failed import calibration fit"
msgstr ""

#: pypilot/boatimu.py:439
msgid "accel values invalid"
msgstr ""

#: pypilot/bufferedsocket.py:55
msgid "overflow in pypilot udp socket"
msgstr ""

#: pypilot/bufferedsocket.py:60
msgid "overflow in pypilot socket"
msgstr ""

#: pypilot/bufferedsocket.py:70
msgid "failed to send udp packet"
msgstr ""

#: pypilot/bufferedsocket.py:79
msgid "pypilot socket failed to send to"
msgstr ""

#: pypilot/bufferedsocket.py:93
msgid "socket send took too long!?!?"
msgstr ""

#: pypilot/bufferedsocket.py:95
msgid "socket send error"
msgstr ""

#: pypilot/bufferedsocket.py:99
msgid "pypilot socket exception"
msgstr ""

#: pypilot/bufferedsocket.py:103
msgid "falling back to python nonblocking socket, will consume more cpu"
msgstr ""

#: pypilot/bufferedsocket.py:129
msgid "socket send error in server flush"
msgstr ""

#: pypilot/bufferedsocket.py:144
msgid "error receiving data"
msgstr ""

#: pypilot/calibration_fit.py:38
msgid "failed to load scientific library, cannot perform calibration update!"
msgstr ""

#: pypilot/client.py:96
msgid "warning, registering existing value:"
msgstr ""

#: pypilot/client.py:157
msgid "failed to read config file:"
msgstr ""

#: pypilot/client.py:188
msgid "failed to write config file:"
msgstr ""

#: pypilot/client.py:190
msgid "Exception writing config file:"
msgstr ""

#: pypilot/client.py:275
msgid "invalid message from server:"
msgstr ""

#: pypilot/client.py:291
msgid "warning, pypilot client aleady has connection"
msgstr ""

#: pypilot/client.py:311
msgid "connect failed to"
msgstr ""

#: pypilot/client.py:403
msgid "failed to connect to"
msgstr ""

#: pypilot/client.py:460
msgid "usage"
msgstr ""

#: pypilot/client.py:463
msgid "set the host or ip address"
msgstr ""

#: pypilot/client.py:464
msgid "print info about each value type"
msgstr ""

#: pypilot/client.py:465
msgid "continuous watch"
msgstr ""

#: pypilot/client.py:466
msgid "show this message"
msgstr ""

#: pypilot/client.py:493
msgid "failed to retrieve value list!"
msgstr ""

#: pypilot/client.py:504
msgid "timeout retrieving"
msgstr ""

#: pypilot/client.py:507
msgid "missing"
msgstr ""

#: pypilot/failedimports.py:12
msgid ""
"pypilot failed to import required modules.  Did you forget to run sudo "
"python3 setup.py install?"
msgstr ""

#: pypilot/gpsd.py:45
msgid "gpsd connected"
msgstr ""

#: pypilot/gpsd.py:49
msgid "gpsd failed to connect"
msgstr ""

#: pypilot/gpsd.py:55
msgid "exception connecting to gps"
msgstr ""

#: pypilot/gpsd.py:59
msgid "gpsd disconnected"
msgstr ""

#: pypilot/gpsd.py:73
msgid "gpsd PROBE success"
msgstr ""

#: pypilot/gpsd.py:81
msgid "gpsd probe failed"
msgstr ""

#: pypilot/gpsd.py:104
msgid "gpsd deactivated"
msgstr ""

#: pypilot/gpsd.py:137
msgid "gpsd failed to determine serial baud rate of device"
msgstr ""

#: pypilot/gpsd.py:154
msgid "gpsd timeout from lack of data"
msgstr ""

#: pypilot/gpsd.py:169
msgid "gpsd received invalid message"
msgstr ""

#: pypilot/gpsd.py:214
msgid "gpsd got flag for pipe:"
msgstr ""

#: pypilot/gpsd.py:223
msgid "gpsd serial probe"
msgstr ""

#: pypilot/nmea.py:86
msgid "nmea failed to parse gps"
msgstr ""

#: pypilot/nmea.py:126
msgid "nmea failed to parse wind"
msgstr ""

#: pypilot/nmea.py:188
msgid "exception parsing apb"
msgstr ""

#: pypilot/nmea.py:276
msgid "unhandled nmea pipe string"
msgstr ""

#: pypilot/nmea.py:326
msgid "lost serial"
msgstr ""

#: pypilot/nmea.py:349
msgid "nmea got flag for process pipe:"
msgstr ""

#: pypilot/nmea.py:370
msgid "is another process accessing it?"
msgstr ""

#: pypilot/nmea.py:372
msgid "serial device timed out"
msgstr ""

#: pypilot/nmea.py:428
msgid "failed to open"
msgstr ""

#: pypilot/nmea.py:484
msgid "nmea server on port"
msgstr ""

#: pypilot/nmea.py:484
msgid "bind failed."
msgstr ""

#: pypilot/nmea.py:486
msgid "listening on port"
msgstr ""

#: pypilot/nmea.py:486
msgid "for nmea connections"
msgstr ""

#: pypilot/nmea.py:552
msgid "nmea server has too many connections"
msgstr ""

#: pypilot/nmea.py:578
msgid "nmea client lost connection"
msgstr ""

#: pypilot/nmea.py:583
msgid "nmea sock not in sockets!"
msgstr ""

#: pypilot/nmea.py:594
msgid "nmea failed to unregister socket"
msgstr ""

#: pypilot/nmea.py:599
msgid "nmea failed to remove fd"
msgstr ""

#: pypilot/nmea.py:604
msgid "nmea failed to remove address"
msgstr ""

#: pypilot/nmea.py:629
msgid "invalid value"
msgstr ""

#: pypilot/nmea.py:639
msgid "connect error"
msgstr ""

#: pypilot/nmea.py:668 pypilot/signalk.py:239
msgid "failed to connect"
msgstr ""

#: pypilot/nmea.py:676
msgid "nmea client connected"
msgstr ""

#: pypilot/nmea.py:705
msgid "poll took too long in nmea process!"
msgstr ""

#: pypilot/nmea.py:712
msgid "nmea bridge lost server connection"
msgstr ""

#: pypilot/nmea.py:715
msgid "nmea bridge lost pipe to autopilot"
msgstr ""

#: pypilot/nmea.py:738
msgid "nmea bridge unhandled poll flag"
msgstr ""

#: pypilot/nmea.py:773
msgid "nmea process loop too slow:"
msgstr ""

#: pypilot/nonblockingpipe.py:40
msgid "error pipe block on recv!"
msgstr ""

#: pypilot/nonblockingpipe.py:42
msgid "failed to recv nonblocking pipe!"
msgstr ""

#: pypilot/nonblockingpipe.py:69
msgid "pipe full"
msgstr ""

#: pypilot/nonblockingpipe.py:69
msgid "cannot send"
msgstr ""

#: pypilot/nonblockingpipe.py:89 pypilot/nonblockingpipe.py:145
msgid "failed to decode data socket!"
msgstr ""

#: pypilot/nonblockingpipe.py:103
msgid "failed to encode data socket!"
msgstr ""

#: pypilot/nonblockingpipe.py:155
msgid "failed write"
msgstr ""

#: pypilot/pyjson.py:14
msgid "WARNING: python ujson library failed, parsing will consume more cpu"
msgstr ""

#: pypilot/rudder.py:117
msgid "bad rudder calibration"
msgstr ""

#: pypilot/rudder.py:121
msgid "bad servo rudder calibration"
msgstr ""

#: pypilot/rudder.py:192
msgid "servo rudder autogain failed"
msgstr ""

#: pypilot/sensors.py:41
msgid "sensor found"
msgstr ""

#: pypilot/sensors.py:190
msgid "unknown data parsed!"
msgstr ""

#: pypilot/serialprobe.py:30
msgid "error reading"
msgstr ""

#: pypilot/serialprobe.py:86
msgid "found more devices by path"
msgstr ""

#: pypilot/serialprobe.py:118
msgid "removing gps device"
msgstr ""

#: pypilot/serialprobe.py:194
msgid "no pyudev module! will scan usb devices often!"
msgstr ""

#: pypilot/serialprobe.py:356
msgid "success"
msgstr ""

#: pypilot/serialprobe.py:364
msgid "failed to record device"
msgstr ""

#: pypilot/server.py:96
msgid "ERROR no connections in watch"
msgstr ""

#: pypilot/server.py:199
msgid "remove duplicate udp connection"
msgstr ""

#: pypilot/server.py:340
msgid "creating config directory: "
msgstr ""

#: pypilot/server.py:347 ui/boatplot.py:109
msgid "failed to load"
msgstr ""

#: pypilot/server.py:358
msgid "backup data failed as well"
msgstr ""

#: pypilot/server.py:386
msgid "failed to write"
msgstr ""

#: pypilot/server.py:443
msgid "pypilot_server: bind failed; already running a server?"
msgstr ""

#: pypilot/server.py:505
msgid "persistent store took too long!"
msgstr ""

#: pypilot/server.py:521
msgid "max connections reached"
msgstr ""

#: pypilot/server.py:524
msgid "server add socket"
msgstr ""

#: pypilot/server.py:534
msgid "internal pipe closed, server exiting"
msgstr ""

#: pypilot/server.py:586
msgid "server socket closed from flush!!"
msgstr ""

#: pypilot/servo.py:460
msgid "servo calibration invalid"
msgstr ""

#: pypilot/servo.py:589
msgid "failed to open servo on:"
msgstr ""

#: pypilot/servo.py:596
msgid "failed set nonblocking/exclusive"
msgstr ""

#: pypilot/servo.py:627 pypilot/signalk.py:159
msgid "found"
msgstr ""

#: pypilot/servo.py:749
msgid "loading servo calibration"
msgstr ""

#: pypilot/servo.py:753
msgid "WARNING: using default servo calibration!!"
msgstr ""

#: pypilot/servo.py:762
msgid "probing"
msgstr ""

#: pypilot/servo.py:778
msgid "arduino servo detected"
msgstr ""

#: pypilot/servo.py:787
msgid "device needed for option"
msgstr ""

#: pypilot/signalk.py:66
msgid "read token"
msgstr ""

#: pypilot/signalk.py:69
msgid "failed to read token"
msgstr ""

#: pypilot/signalk.py:76
msgid "failed to"
msgstr ""

#: pypilot/signalk.py:76
msgid "autodetection not possible"
msgstr ""

#: pypilot/signalk.py:77 pypilot/signalk.py:146 pypilot/signalk.py:216
msgid "try"
msgstr ""

#: pypilot/signalk.py:77 pypilot/signalk.py:146 pypilot/signalk.py:216
msgid "or"
msgstr ""

#: pypilot/signalk.py:108
msgid "service removed"
msgstr ""

#: pypilot/signalk.py:112
msgid "server lost"
msgstr ""

#: pypilot/signalk.py:118
msgid "service add"
msgstr ""

#: pypilot/signalk.py:132
msgid "server found"
msgstr ""

#: pypilot/signalk.py:141
msgid "probe"
msgstr ""

#: pypilot/signalk.py:145
msgid "could not"
msgstr ""

#: pypilot/signalk.py:155
msgid "failed to retrieve/parse data from"
msgstr ""

#: pypilot/signalk.py:171
msgid "see if token is ready"
msgstr ""

#: pypilot/signalk.py:177
msgid "received token"
msgstr ""

#: pypilot/signalk.py:183
msgid "failed to store token"
msgstr ""

#: pypilot/signalk.py:187 pypilot/signalk.py:208
msgid "error requesting access"
msgstr ""

#: pypilot/signalk.py:206
msgid "request access url"
msgstr ""

#: pypilot/signalk.py:215
msgid "cannot create connection:"
msgstr ""

#: pypilot/signalk.py:230
msgid "bad status, rejecting token"
msgstr ""

#: pypilot/signalk.py:234
msgid "connection refused"
msgstr ""

#: pypilot/signalk.py:284
msgid "connected to"
msgstr ""

#: pypilot/signalk.py:354
msgid "Exception converting signalk->pypilot"
msgstr ""

#: pypilot/signalk.py:368
msgid "received"
msgstr ""

#: pypilot/signalk.py:414
msgid "failed to send updates"
msgstr ""

#: pypilot/signalk.py:428
msgid "failed to parse msg:"
msgstr ""

#: pypilot/values.py:130
msgid "invalid initial value for range property"
msgstr ""

#: pypilot/values.py:179
msgid "invalid set"
msgstr ""

#: pypilot/pilots/__init__.py:23
msgid "ERROR loading"
msgstr ""

#: ui/autopilot_calibration.py:166
msgid "exception in calibration:"
msgstr ""

#: ui/autopilot_control.py:264
msgid "warning: unhandled message"
msgstr ""

#: ui/autopilot_control_ui.py:24
msgid "Autopilot Control"
msgstr ""

#: ui/autopilot_control_ui.py:39
msgid "AP"
msgstr ""

#: ui/autopilot_control_ui.py:57 ui/autopilot_control_ui.py:67
#: ui/autopilot_control_ui.py:460 ui/autopilot_control_ui.py:737
msgid "N/A"
msgstr ""

#: ui/autopilot_control_ui.py:62
msgid "        N/A        "
msgstr ""

#: ui/autopilot_control_ui.py:74
msgid "----"
msgstr ""

#: ui/autopilot_control_ui.py:89 ui/autopilot_control_ui.py:96
msgid " N/A "
msgstr ""

#: ui/autopilot_control_ui.py:121
msgid "port"
msgstr ""

#: ui/autopilot_control_ui.py:121
msgid "starboard"
msgstr ""

#: ui/autopilot_control_ui.py:136
msgid "Pilot"
msgstr ""

#: ui/autopilot_control_ui.py:146 ui/autopilot_control_ui.py:425
msgid "Compass"
msgstr ""

#: ui/autopilot_control_ui.py:149
msgid "GPS"
msgstr ""

#: ui/autopilot_control_ui.py:154
msgid "Wind"
msgstr ""

#: ui/autopilot_control_ui.py:159
msgid "True Wind"
msgstr ""

#: ui/autopilot_control_ui.py:175 ui/scope_ui.py:76
msgid "Center"
msgstr ""

#: ui/autopilot_control_ui.py:199
msgid "&Scope"
msgstr ""

#: ui/autopilot_control_ui.py:202
msgid "&Client"
msgstr ""

#: ui/autopilot_control_ui.py:205
msgid "C&alibration"
msgstr ""

#: ui/autopilot_control_ui.py:208 ui/scope_ui.py:108
msgid "Close"
msgstr ""

#: ui/autopilot_control_ui.py:304 ui/autopilot_control_ui.py:534
#: ui/autopilot_control_ui.py:654
msgid "Calibration"
msgstr ""

#: ui/autopilot_control_ui.py:354
msgid "Boat is level"
msgstr ""

#: ui/autopilot_control_ui.py:361 ui/client_wx.py:158 ui/scope_ui.py:94
msgid "Reset"
msgstr ""

#: ui/autopilot_control_ui.py:382
msgid "Alignment"
msgstr ""

#: ui/autopilot_control_ui.py:399
msgid "Heading"
msgstr ""

#: ui/autopilot_control_ui.py:404 ui/autopilot_control_ui.py:470
#: ui/autopilot_control_ui.py:480
msgid "     N/A     "
msgstr ""

#: ui/autopilot_control_ui.py:409 ui/autopilot_control_ui.py:760
msgid "Offset"
msgstr ""

#: ui/autopilot_control_ui.py:423
msgid "Coords"
msgstr ""

#: ui/autopilot_control_ui.py:425
msgid "Sea"
msgstr ""

#: ui/autopilot_control_ui.py:425
msgid "Boat"
msgstr ""

#: ui/autopilot_control_ui.py:448 ui/client_wx.py:51
msgid "Scope"
msgstr ""

#: ui/autopilot_control_ui.py:455
msgid "Pitch"
msgstr ""

#: ui/autopilot_control_ui.py:465
msgid "Roll"
msgstr ""

#: ui/autopilot_control_ui.py:475
msgid "Heel"
msgstr ""

#: ui/autopilot_control_ui.py:502
msgid "alignment"
msgstr ""

#: ui/autopilot_control_ui.py:544 ui/autopilot_control_ui.py:664
msgid "Calibration Age"
msgstr ""

#: ui/autopilot_control_ui.py:561 ui/autopilot_control_ui.py:681
msgid "Clear"
msgstr ""

#: ui/autopilot_control_ui.py:564 ui/autopilot_control_ui.py:684
msgid "calibration locked"
msgstr ""

#: ui/autopilot_control_ui.py:587
msgid "accel"
msgstr ""

#: ui/autopilot_control_ui.py:618
msgid "Sigma Points"
msgstr ""

#: ui/autopilot_control_ui.py:625
msgid "local history"
msgstr ""

#: ui/autopilot_control_ui.py:632
msgid "current"
msgstr ""

#: ui/autopilot_control_ui.py:639
msgid "Calibration Points"
msgstr ""

#: ui/autopilot_control_ui.py:708
msgid "compass"
msgstr ""

#: ui/autopilot_control_ui.py:718
msgid "Press each button when the rudder is at the correct position to calibrate."
msgstr ""

#: ui/autopilot_control_ui.py:732
msgid "Rudder"
msgstr ""

#: ui/autopilot_control_ui.py:747
msgid "Reset Calibration"
msgstr ""

#: ui/autopilot_control_ui.py:757
msgid "Rudder Is Centered"
msgstr ""

#: ui/autopilot_control_ui.py:765 ui/autopilot_control_ui.py:778
#: ui/autopilot_control_ui.py:791
msgid "------"
msgstr ""

#: ui/autopilot_control_ui.py:770
msgid "Rudder is Starboard Range"
msgstr ""

#: ui/autopilot_control_ui.py:773
msgid "Scale"
msgstr ""

#: ui/autopilot_control_ui.py:783
msgid "Rudder is Port Range"
msgstr ""

#: ui/autopilot_control_ui.py:786
msgid "Non Linearity"
msgstr ""

#: ui/autopilot_control_ui.py:803
msgid " range +-"
msgstr ""

#: ui/autopilot_control_ui.py:811
msgid "degrees"
msgstr ""

#: ui/autopilot_control_ui.py:830
msgid "rudder"
msgstr ""

#: ui/autopilot_control_ui.py:832
msgid "settings"
msgstr ""

#: ui/boatplot.py:25
msgid "failed to load pywavefront:"
msgstr ""

#: ui/boatplot.py:55
msgid "invalid display dimensions"
msgstr ""

#: ui/boatplot.py:110
msgid "Did you add the pypilot_data repository?"
msgstr ""

#: ui/boatplot.py:160
msgid "not found, texture compass cannot be used"
msgstr ""

#: ui/client_wx.py:47
msgid "Refresh"
msgstr ""

#: ui/client_wx.py:189
msgid "Connected"
msgstr ""

#: ui/client_wx.py:191
msgid "Disconnected"
msgstr ""

#: ui/client_wx.py:218
msgid "warning, invalid choice value specified"
msgstr ""

#: ui/scope_ui.py:24
msgid "pypilot Scope"
msgstr ""

#: ui/scope_ui.py:73
msgid "Zero"
msgstr ""

#: ui/scope_ui.py:79
msgid "Scale +"
msgstr ""

#: ui/scope_ui.py:82
msgid "Scale -"
msgstr ""

#: ui/scope_ui.py:85
msgid "Offset /\\"
msgstr ""

#: ui/scope_ui.py:88
msgid "Offset \\/"
msgstr ""

#: ui/scope_ui.py:91
msgid "Freeze"
msgstr ""

#: ui/scope_ui.py:97
msgid "fftw"
msgstr ""

#: ui/scope_ui.py:100
msgid "Time"
msgstr ""

#: ui/scope_wx.py:67
msgid "values not found:"
msgstr ""

