# Translations template for pypilot.
# Copyright (C) 2021 ORGANIZATION
# This file is distributed under the same license as the pypilot project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2021.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: pypilot 0.24\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2021-09-18 00:31-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"Generated-By: Babel 2.6.0\n"

#: pypilot/autopilot.py:139
msgid "Available Pilots"
msgstr "Dostępni piloci"

#: pypilot/autopilot.py:161
msgid "warning: failed to open special file"
msgstr "ostrzeżenie: nie udało się otworzyć specjalnego pliku"

#: pypilot/autopilot.py:161
msgid "for writing"
msgstr "do pisania"

#: pypilot/autopilot.py:162
msgid "cannot stroke the watchdog"
msgstr "nie mogę pogłaskać psa stróżującego"

#: pypilot/autopilot.py:166
msgid "warning: failed to make autopilot process realtime"
msgstr ""
"ostrzeżenie: nie udało się wykonać procesu autopilota w czasie rzeczywistym"

#: pypilot/autopilot.py:337
msgid "server/client is running too _slowly_"
msgstr "serwer/klient działa zbyt _wolno_"

#: pypilot/autopilot.py:343
msgid "sensors is running too _slowly_"
msgstr "czujniki działają zbyt wolno"

#: pypilot/autopilot.py:420
msgid "autopilot routine is running too _slowly_"
msgstr "Procedura autopilota działa zbyt wolno"

#: pypilot/autopilot.py:429
msgid "servo is running too _slowly_"
msgstr "serwo działa zbyt wolno"

#: pypilot/boatimu.py:33
msgid "RTIMU library not detected, please install it"
msgstr "Nie wykryto biblioteki RTIMU, zainstaluj ją"

#: pypilot/boatimu.py:56
msgid "Using settings file"
msgstr "Korzystanie z pliku ustawień"

#: pypilot/boatimu.py:96
msgid "ERROR: No IMU Detected"
msgstr "BŁĄD: Nie wykryto IMU"

#: pypilot/boatimu.py:104
msgid "ERROR: IMU Init Failed, no inertial data available"
msgstr "BŁĄD: IMU Init Failed, brak dostępnych danych inercyjnych"

#: pypilot/boatimu.py:126
msgid "warning, failed to make imu process realtime"
msgstr "ostrzeżenie, nie udało się wykonać procesu imu w czasie rzeczywistym"

#: pypilot/boatimu.py:128
msgid "made imu process realtime"
msgstr "wykonane imu proces w czasie rzeczywistym"

#: pypilot/boatimu.py:140
msgid "setting initial gyro bias"
msgstr "ustawienie początkowego odchylenia żyroskopu"

#: pypilot/boatimu.py:156
msgid "imu process failed to keep time"
msgstr "Proces imu nie dotrzymał czasu"

#: pypilot/boatimu.py:164
msgid "failed to read IMU!"
msgstr "nie udało się odczytać IMU!"

#: pypilot/boatimu.py:196
msgid "imu rate set to rate"
msgstr "stawka imu ustawiona na stawkę"

#: pypilot/boatimu.py:210
msgid "too high standing gyro bias, resetting sensors"
msgstr "zbyt wysokie odchylenie stojące żyroskopu, resetowanie czujników"

#: pypilot/boatimu.py:215
msgid "compass out of range, resetting"
msgstr "kompas poza zasięgiem, resetowanie"

#: pypilot/boatimu.py:307
msgid "warning, failed to make calibration process other"
msgstr "ostrzeżenie, nie udało się dokonać kalibracji w inny sposób"

#: pypilot/boatimu.py:309
msgid "warning, failed to make calibration process idle, trying renice"
msgstr ""
"ostrzeżenie, nie udało się przeprowadzić procesu kalibracji bezczynności, "
"próbuję renice"

#: pypilot/boatimu.py:311
msgid "warning, failed to renice calibration process"
msgstr "ostrzeżenie, nie udało się odnowić procesu kalibracji"

#: pypilot/boatimu.py:318
msgid "calibration loaded, starting"
msgstr "kalibracja załadowana, start"

#: pypilot/boatimu.py:322
msgid "failed import calibration fit"
msgstr "nieudane dopasowanie kalibracji importu"

#: pypilot/boatimu.py:439
msgid "accel values invalid"
msgstr "wartości przyspieszenia są nieprawidłowe"

#: pypilot/bufferedsocket.py:55
msgid "overflow in pypilot udp socket"
msgstr "przepełnienie w gnieździe pypilot udp"

#: pypilot/bufferedsocket.py:60
msgid "overflow in pypilot socket"
msgstr "przelew w gnieździe pypilota"

#: pypilot/bufferedsocket.py:70
msgid "failed to send udp packet"
msgstr "nie udało się wysłać pakietu UDP"

#: pypilot/bufferedsocket.py:79
msgid "pypilot socket failed to send to"
msgstr "Nie udało się wysłać gniazda pypilot do"

#: pypilot/bufferedsocket.py:93
msgid "socket send took too long!?!?"
msgstr "wysyłanie gniazda trwało zbyt długo!?!?"

#: pypilot/bufferedsocket.py:95
msgid "socket send error"
msgstr "Błąd wysyłania gniazda"

#: pypilot/bufferedsocket.py:99
msgid "pypilot socket exception"
msgstr "Wyjątek gniazda pypilot"

#: pypilot/bufferedsocket.py:103
msgid "falling back to python nonblocking socket, will consume more cpu"
msgstr "powrót do nieblokującego gniazda Pythona, zużyje więcej procesora c"

#: pypilot/bufferedsocket.py:129
msgid "socket send error in server flush"
msgstr "błąd wysyłania gniazda w spłukiwaniu serwera"

#: pypilot/bufferedsocket.py:144
msgid "error receiving data"
msgstr "błąd odbierania danych"

#: pypilot/calibration_fit.py:38
msgid "failed to load scientific library, cannot perform calibration update!"
msgstr ""
"nie udało się załadować biblioteki naukowej, nie można przeprowadzić "
"aktualizacji kalibracji!"

#: pypilot/client.py:96
msgid "warning, registering existing value:"
msgstr "ostrzeżenie, rejestracja istniejącej wartości:"

#: pypilot/client.py:157
msgid "failed to read config file:"
msgstr "nie udało się odczytać pliku konfiguracyjnego:"

#: pypilot/client.py:188
msgid "failed to write config file:"
msgstr "nie udało się zapisać pliku konfiguracyjnego:"

#: pypilot/client.py:190
msgid "Exception writing config file:"
msgstr "Plik konfiguracyjny zapisu wyjątków:"

#: pypilot/client.py:275
msgid "invalid message from server:"
msgstr "nieprawidłowa wiadomość z serwera:"

#: pypilot/client.py:291
msgid "warning, pypilot client aleady has connection"
msgstr "ostrzeżenie, klient pypilot ma już połączenie"

#: pypilot/client.py:311
msgid "connect failed to"
msgstr "nie udało się połączyć z"

#: pypilot/client.py:403
msgid "failed to connect to"
msgstr "nie udało się połączyć z"

#: pypilot/client.py:460
msgid "usage"
msgstr "stosowanie"

#: pypilot/client.py:463
msgid "set the host or ip address"
msgstr "ustaw hosta lub adres IP"

#: pypilot/client.py:464
msgid "print info about each value type"
msgstr "drukuj informacje o każdym typie wartości"

#: pypilot/client.py:465
msgid "continuous watch"
msgstr "obserwacja ciągła ."

#: pypilot/client.py:466
msgid "show this message"
msgstr "pokaż tę wiadomość"

#: pypilot/client.py:493
msgid "failed to retrieve value list!"
msgstr "nie udało się pobrać listy wartości!"

#: pypilot/client.py:504
msgid "timeout retrieving"
msgstr "Pobieranie limitu czasu"

#: pypilot/client.py:507
msgid "missing"
msgstr "brakujący"

#: pypilot/failedimports.py:12
msgid ""
"pypilot failed to import required modules.  Did you forget to run sudo "
"python3 setup.py install?"
msgstr ""
"pypilot nie mógł zaimportować wymaganych modułów. Zapomniałeś uruchomić sudo "
"python3 setup.py install?"

#: pypilot/gpsd.py:45
msgid "gpsd connected"
msgstr "podłączony GPS"

#: pypilot/gpsd.py:49
msgid "gpsd failed to connect"
msgstr "GPSd nie udało się połączyć"

#: pypilot/gpsd.py:55
msgid "exception connecting to gps"
msgstr "wyjątek w połączeniu z GPS"

#: pypilot/gpsd.py:59
msgid "gpsd disconnected"
msgstr "GPS odłączony"

#: pypilot/gpsd.py:73
msgid "gpsd PROBE success"
msgstr "Sukces SONDY GPS"

#: pypilot/gpsd.py:81
msgid "gpsd probe failed"
msgstr "sonda gpsd nie powiodła się"

#: pypilot/gpsd.py:104
msgid "gpsd deactivated"
msgstr "GPS dezaktywowany"

#: pypilot/gpsd.py:137
msgid "gpsd failed to determine serial baud rate of device"
msgstr "GPSd nie może określić szybkości transmisji szeregowej urządzenia"

#: pypilot/gpsd.py:154
msgid "gpsd timeout from lack of data"
msgstr "przekroczenie limitu czasu gpsd z powodu braku danych"

#: pypilot/gpsd.py:169
msgid "gpsd received invalid message"
msgstr "gpsd otrzymał nieprawidłową wiadomość"

#: pypilot/gpsd.py:214
msgid "gpsd got flag for pipe:"
msgstr "gpsd ma flagę dla potoku:"

#: pypilot/gpsd.py:223
msgid "gpsd serial probe"
msgstr "sonda szeregowa gpsd"

#: pypilot/nmea.py:86
msgid "nmea failed to parse gps"
msgstr "nmea nie przeanalizowała GPS"

#: pypilot/nmea.py:126
msgid "nmea failed to parse wind"
msgstr "nmea nie przeanalizowała wiatru"

#: pypilot/nmea.py:188
msgid "exception parsing apb"
msgstr "parsowanie wyjątków apb"

#: pypilot/nmea.py:276
msgid "unhandled nmea pipe string"
msgstr "nieobsługiwany ciąg rur nmea"

#: pypilot/nmea.py:326
msgid "lost serial"
msgstr "zgubiony serial"

#: pypilot/nmea.py:349
msgid "nmea got flag for process pipe:"
msgstr "nmea otrzymała flagę dla rury procesowej:"

#: pypilot/nmea.py:370
msgid "is another process accessing it?"
msgstr "czy inny proces ma do niego dostęp?"

#: pypilot/nmea.py:372
msgid "serial device timed out"
msgstr "Przekroczono limit czasu urządzenia szeregowego"

#: pypilot/nmea.py:428
msgid "failed to open"
msgstr "nie udało się otworzyć"

#: pypilot/nmea.py:484
msgid "nmea server on port"
msgstr "serwer nmea na porcie"

#: pypilot/nmea.py:484
msgid "bind failed."
msgstr "powiązanie nie powiodło się."

#: pypilot/nmea.py:486
msgid "listening on port"
msgstr "nasłuchiwanie na porcie"

#: pypilot/nmea.py:486
msgid "for nmea connections"
msgstr "dla połączeń nmea"

#: pypilot/nmea.py:552
msgid "nmea server has too many connections"
msgstr "Serwer nmea ma za dużo połączeń"

#: pypilot/nmea.py:578
msgid "nmea client lost connection"
msgstr "Klient nmea utracił połączenie"

#: pypilot/nmea.py:583
msgid "nmea sock not in sockets!"
msgstr "skarpeta nmea nie jest w gniazdkach!"

#: pypilot/nmea.py:594
msgid "nmea failed to unregister socket"
msgstr "nmea nie może wyrejestrować gniazda"

#: pypilot/nmea.py:599
msgid "nmea failed to remove fd"
msgstr "nmea nie usunął fd"

#: pypilot/nmea.py:604
msgid "nmea failed to remove address"
msgstr "nmea nie udało się usunąć adresu"

#: pypilot/nmea.py:629
msgid "invalid value"
msgstr "niewłaściwa wartość"

#: pypilot/nmea.py:639
msgid "connect error"
msgstr "błąd połączenia"

#: pypilot/nmea.py:668 pypilot/signalk.py:239
msgid "failed to connect"
msgstr "nie udało się połączyć"

#: pypilot/nmea.py:676
msgid "nmea client connected"
msgstr "Podłączono klienta nmea"

#: pypilot/nmea.py:705
msgid "poll took too long in nmea process!"
msgstr "ankieta trwała zbyt długo w procesie nmea!"

#: pypilot/nmea.py:712
msgid "nmea bridge lost server connection"
msgstr "nmea most utracił połączenie z serwerem"

#: pypilot/nmea.py:715
msgid "nmea bridge lost pipe to autopilot"
msgstr "most nmea zgubił rurę do autopilota"

#: pypilot/nmea.py:738
msgid "nmea bridge unhandled poll flag"
msgstr "nmea bridge nieobsłużona flaga ankiety"

#: pypilot/nmea.py:773
msgid "nmea process loop too slow:"
msgstr "Zbyt wolna pętla procesu nmea:"

#: pypilot/nonblockingpipe.py:40
msgid "error pipe block on recv!"
msgstr "błąd bloku potoku na recv!"

#: pypilot/nonblockingpipe.py:42
msgid "failed to recv nonblocking pipe!"
msgstr "nie udało się odebrać nieblokującego potoku!"

#: pypilot/nonblockingpipe.py:69
msgid "pipe full"
msgstr "rura pełna"

#: pypilot/nonblockingpipe.py:69
msgid "cannot send"
msgstr "nie można wysłać"

#: pypilot/nonblockingpipe.py:89 pypilot/nonblockingpipe.py:145
msgid "failed to decode data socket!"
msgstr "nie udało się zdekodować gniazda danych!"

#: pypilot/nonblockingpipe.py:103
msgid "failed to encode data socket!"
msgstr "nie udało się zakodować gniazda danych!"

#: pypilot/nonblockingpipe.py:155
msgid "failed write"
msgstr "nieudany zapis"

#: pypilot/pyjson.py:14
msgid "WARNING: python ujson library failed, parsing will consume more cpu"
msgstr ""
"OSTRZEŻENIE: biblioteka Pythona ujson nie powiodła się, parsowanie zużyje "
"więcej procesora"

#: pypilot/rudder.py:117
msgid "bad rudder calibration"
msgstr "zła kalibracja steru"

#: pypilot/rudder.py:121
msgid "bad servo rudder calibration"
msgstr "zła kalibracja steru serwomechanizmu"

#: pypilot/rudder.py:192
msgid "servo rudder autogain failed"
msgstr "Autowzmocnienie steru serwomechanizmu nie powiodło się"

#: pypilot/sensors.py:41
msgid "sensor found"
msgstr "znaleziono czujnik"

#: pypilot/sensors.py:190
msgid "unknown data parsed!"
msgstr "przeanalizowano nieznane dane!"

#: pypilot/serialprobe.py:30
msgid "error reading"
msgstr "błąd odczytu"

#: pypilot/serialprobe.py:86
msgid "found more devices by path"
msgstr "znalazłem więcej urządzeń według ścieżki"

#: pypilot/serialprobe.py:118
msgid "removing gps device"
msgstr "usuwanie urządzenia GPS"

#: pypilot/serialprobe.py:194
msgid "no pyudev module! will scan usb devices often!"
msgstr "brak modułu pyudev! będzie często skanować urządzenia USB!"

#: pypilot/serialprobe.py:356
msgid "success"
msgstr "sukces"

#: pypilot/serialprobe.py:364
msgid "failed to record device"
msgstr "nie udało się nagrać urządzenia"

#: pypilot/server.py:96
msgid "ERROR no connections in watch"
msgstr "BŁĄD brak połączeń w zegarku"

#: pypilot/server.py:199
msgid "remove duplicate udp connection"
msgstr "usuń zduplikowane połączenie UDP"

#: pypilot/server.py:340
msgid "creating config directory: "
msgstr "tworzenie katalogu konfiguracyjnego:"

#: pypilot/server.py:347 ui/boatplot.py:109
msgid "failed to load"
msgstr "nie udało się załadować"

#: pypilot/server.py:358
msgid "backup data failed as well"
msgstr "kopia zapasowa również nie powiodła się"

#: pypilot/server.py:386
msgid "failed to write"
msgstr "nie udało się napisać"

#: pypilot/server.py:443
msgid "pypilot_server: bind failed; already running a server?"
msgstr "pypilot_server: wiązanie nie powiodło się; masz już serwer?"

#: pypilot/server.py:505
msgid "persistent store took too long!"
msgstr "uporczywe przechowywanie trwało zbyt długo!"

#: pypilot/server.py:521
msgid "max connections reached"
msgstr "osiągnięto maksymalną liczbę połączeń"

#: pypilot/server.py:524
msgid "server add socket"
msgstr "serwer dodaj gniazdo"

#: pypilot/server.py:534
msgid "internal pipe closed, server exiting"
msgstr "rura wewnętrzna zamknięta, serwer wychodzi server"

#: pypilot/server.py:586
msgid "server socket closed from flush!!"
msgstr "gniazdo serwera zamknięte od spłukiwania!!"

#: pypilot/servo.py:460
msgid "servo calibration invalid"
msgstr "kalibracja serwa jest nieprawidłowa"

#: pypilot/servo.py:589
msgid "failed to open servo on:"
msgstr "nie udało się otworzyć serwa na:"

#: pypilot/servo.py:596
msgid "failed set nonblocking/exclusive"
msgstr "nieudane ustawienie nieblokujące/wyłączne"

#: pypilot/servo.py:627 pypilot/signalk.py:159
msgid "found"
msgstr "znaleziony"

#: pypilot/servo.py:749
msgid "loading servo calibration"
msgstr "kalibracja serwomechanizmu ładowania"

#: pypilot/servo.py:753
msgid "WARNING: using default servo calibration!!"
msgstr "UWAGA: używanie domyślnej kalibracji serwa!!"

#: pypilot/servo.py:762
msgid "probing"
msgstr "sondowanie"

#: pypilot/servo.py:778
msgid "arduino servo detected"
msgstr "wykryto serwo arduino"

#: pypilot/servo.py:787
msgid "device needed for option"
msgstr "urządzenie potrzebne do opcji"

#: pypilot/signalk.py:66
msgid "read token"
msgstr "przeczytaj token"

#: pypilot/signalk.py:69
msgid "failed to read token"
msgstr "nie udało się odczytać tokena"

#: pypilot/signalk.py:76
msgid "failed to"
msgstr "nie udało się"

#: pypilot/signalk.py:76
msgid "autodetection not possible"
msgstr "autodetekcja nie jest możliwa"

#: pypilot/signalk.py:77 pypilot/signalk.py:146 pypilot/signalk.py:216
msgid "try"
msgstr "próbować"

#: pypilot/signalk.py:77 pypilot/signalk.py:146 pypilot/signalk.py:216
msgid "or"
msgstr "lub"

#: pypilot/signalk.py:108
msgid "service removed"
msgstr "usługa usunięta"

#: pypilot/signalk.py:112
msgid "server lost"
msgstr "serwer zgubiony"

#: pypilot/signalk.py:118
msgid "service add"
msgstr "usługa add"

#: pypilot/signalk.py:132
msgid "server found"
msgstr "znaleziono serwer"

#: pypilot/signalk.py:141
msgid "probe"
msgstr "sonda"

#: pypilot/signalk.py:145
msgid "could not"
msgstr "nie móc"

#: pypilot/signalk.py:155
msgid "failed to retrieve/parse data from"
msgstr "nie udało się pobrać/przeanalizować danych z"

#: pypilot/signalk.py:171
msgid "see if token is ready"
msgstr "zobacz, czy token jest gotowy"

#: pypilot/signalk.py:177
msgid "received token"
msgstr "otrzymany token"

#: pypilot/signalk.py:183
msgid "failed to store token"
msgstr "nie udało się zapisać tokena"

#: pypilot/signalk.py:187 pypilot/signalk.py:208
msgid "error requesting access"
msgstr "błąd podczas żądania dostępu"

#: pypilot/signalk.py:206
msgid "request access url"
msgstr "poproś o dostęp do adresu URL"

#: pypilot/signalk.py:215
msgid "cannot create connection:"
msgstr "nie można utworzyć połączenia:"

#: pypilot/signalk.py:230
msgid "bad status, rejecting token"
msgstr "zły stan, odrzucanie tokena"

#: pypilot/signalk.py:234
msgid "connection refused"
msgstr "połączenie odrzucone"

#: pypilot/signalk.py:284
msgid "connected to"
msgstr "połączony z"

#: pypilot/signalk.py:354
msgid "Exception converting signalk->pypilot"
msgstr "Wyjątek konwertujący sygnał->pypilot"

#: pypilot/signalk.py:368
msgid "received"
msgstr "Odebrane"

#: pypilot/signalk.py:414
msgid "failed to send updates"
msgstr "nie udało się wysłać aktualizacji"

#: pypilot/signalk.py:428
msgid "failed to parse msg:"
msgstr "nie udało się przeanalizować wiadomości:"

#: pypilot/values.py:130
msgid "invalid initial value for range property"
msgstr "nieprawidłowa wartość początkowa właściwości zakresu range"

#: pypilot/values.py:179
msgid "invalid set"
msgstr "nieprawidłowy zestaw"

#: pypilot/pilots/__init__.py:23
msgid "ERROR loading"
msgstr "Błąd ładowania"

#: ui/autopilot_calibration.py:166
msgid "exception in calibration:"
msgstr "wyjątek w kalibracji:"

#: ui/autopilot_control.py:264
msgid "warning: unhandled message"
msgstr "ostrzeżenie: nieobsłużona wiadomość"

#: ui/autopilot_control_ui.py:24
msgid "Autopilot Control"
msgstr "Kontrola autopilota"

#: ui/autopilot_control_ui.py:39
msgid "AP"
msgstr "ty"

#: ui/autopilot_control_ui.py:57 ui/autopilot_control_ui.py:67
#: ui/autopilot_control_ui.py:460 ui/autopilot_control_ui.py:737
msgid "N/A"
msgstr "Nie dotyczy"

#: ui/autopilot_control_ui.py:62
msgid "        N/A        "
msgstr "Nie dotyczy"

#: ui/autopilot_control_ui.py:74
msgid "----"
msgstr "----"

#: ui/autopilot_control_ui.py:89 ui/autopilot_control_ui.py:96
msgid " N/A "
msgstr "Nie dotyczy"

#: ui/autopilot_control_ui.py:121
msgid "port"
msgstr "Port"

#: ui/autopilot_control_ui.py:121
msgid "starboard"
msgstr "sterburta"

#: ui/autopilot_control_ui.py:136
msgid "Pilot"
msgstr "Pilot"

#: ui/autopilot_control_ui.py:146 ui/autopilot_control_ui.py:425
msgid "Compass"
msgstr "Kompas"

#: ui/autopilot_control_ui.py:149
msgid "GPS"
msgstr "GPS"

#: ui/autopilot_control_ui.py:154
msgid "Wind"
msgstr "Wiatr"

#: ui/autopilot_control_ui.py:159
msgid "True Wind"
msgstr "Prawdziwy wiatr"

#: ui/autopilot_control_ui.py:175 ui/scope_ui.py:76
msgid "Center"
msgstr "Środek"

#: ui/autopilot_control_ui.py:199
msgid "&Scope"
msgstr "&Zakres"

#: ui/autopilot_control_ui.py:202
msgid "&Client"
msgstr "&Klient"

#: ui/autopilot_control_ui.py:205
msgid "C&alibration"
msgstr "K&alibrowanie"

#: ui/autopilot_control_ui.py:208 ui/scope_ui.py:108
msgid "Close"
msgstr "Blisko"

#: ui/autopilot_control_ui.py:304 ui/autopilot_control_ui.py:534
#: ui/autopilot_control_ui.py:654
msgid "Calibration"
msgstr "Kalibrowanie"

#: ui/autopilot_control_ui.py:354
msgid "Boat is level"
msgstr "Łódź jest wypoziomowana"

#: ui/autopilot_control_ui.py:361 ui/client_wx.py:158 ui/scope_ui.py:94
msgid "Reset"
msgstr "Resetowanie"

#: ui/autopilot_control_ui.py:382
msgid "Alignment"
msgstr "Wyrównanie"

#: ui/autopilot_control_ui.py:399
msgid "Heading"
msgstr "Nagłówek"

#: ui/autopilot_control_ui.py:404 ui/autopilot_control_ui.py:470
#: ui/autopilot_control_ui.py:480
msgid "     N/A     "
msgstr "Nie dotyczy"

#: ui/autopilot_control_ui.py:409 ui/autopilot_control_ui.py:760
msgid "Offset"
msgstr "Offsetowy"

#: ui/autopilot_control_ui.py:423
msgid "Coords"
msgstr "Współrzędne"

#: ui/autopilot_control_ui.py:425
msgid "Sea"
msgstr "Morze"

#: ui/autopilot_control_ui.py:425
msgid "Boat"
msgstr "Łódź"

#: ui/autopilot_control_ui.py:448 ui/client_wx.py:51
msgid "Scope"
msgstr "Zakres"

#: ui/autopilot_control_ui.py:455
msgid "Pitch"
msgstr "Smoła"

#: ui/autopilot_control_ui.py:465
msgid "Roll"
msgstr "Rolka"

#: ui/autopilot_control_ui.py:475
msgid "Heel"
msgstr "Obcas"

#: ui/autopilot_control_ui.py:502
msgid "alignment"
msgstr "wyrównanie"

#: ui/autopilot_control_ui.py:544 ui/autopilot_control_ui.py:664
msgid "Calibration Age"
msgstr "Wiek kalibracji"

#: ui/autopilot_control_ui.py:561 ui/autopilot_control_ui.py:681
msgid "Clear"
msgstr "Jasny"

#: ui/autopilot_control_ui.py:564 ui/autopilot_control_ui.py:684
msgid "calibration locked"
msgstr "kalibracja zablokowana"

#: ui/autopilot_control_ui.py:587
msgid "accel"
msgstr "przyspieszać"

#: ui/autopilot_control_ui.py:618
msgid "Sigma Points"
msgstr "Punkty Sigma"

#: ui/autopilot_control_ui.py:625
msgid "local history"
msgstr "lokalna historia"

#: ui/autopilot_control_ui.py:632
msgid "current"
msgstr "obecny"

#: ui/autopilot_control_ui.py:639
msgid "Calibration Points"
msgstr "Punkty kalibracji"

#: ui/autopilot_control_ui.py:708
msgid "compass"
msgstr "kompas"

#: ui/autopilot_control_ui.py:718
msgid ""
"Press each button when the rudder is at the correct position to calibrate."
msgstr ""
"Naciśnij każdy przycisk, gdy ster znajduje się w prawidłowej pozycji, aby "
"przeprowadzić kalibrację."

#: ui/autopilot_control_ui.py:732
msgid "Rudder"
msgstr "Ster"

#: ui/autopilot_control_ui.py:747
msgid "Reset Calibration"
msgstr "Zresetuj kalibrację"

#: ui/autopilot_control_ui.py:757
msgid "Rudder Is Centered"
msgstr "Ster jest wyśrodkowany"

#: ui/autopilot_control_ui.py:765 ui/autopilot_control_ui.py:778
#: ui/autopilot_control_ui.py:791
msgid "------"
msgstr "------"

#: ui/autopilot_control_ui.py:770
msgid "Rudder is Starboard Range"
msgstr "Ster ma zasięg na sterburcie"

#: ui/autopilot_control_ui.py:773
msgid "Scale"
msgstr "Skala"

#: ui/autopilot_control_ui.py:783
msgid "Rudder is Port Range"
msgstr "Ster ma zakres lewy ."

#: ui/autopilot_control_ui.py:786
msgid "Non Linearity"
msgstr "Nieliniowość"

#: ui/autopilot_control_ui.py:803
msgid " range +-"
msgstr "zasięg +-"

#: ui/autopilot_control_ui.py:811
msgid "degrees"
msgstr "stopnie"

#: ui/autopilot_control_ui.py:830
msgid "rudder"
msgstr "ster"

#: ui/autopilot_control_ui.py:832
msgid "settings"
msgstr "ustawienia"

#: ui/boatplot.py:25
msgid "failed to load pywavefront:"
msgstr "nie udało się załadować pywavefronta:"

#: ui/boatplot.py:55
msgid "invalid display dimensions"
msgstr "nieprawidłowe wymiary wyświetlacza"

#: ui/boatplot.py:110
msgid "Did you add the pypilot_data repository?"
msgstr "Czy dodałeś repozytorium pypilot_data?"

#: ui/boatplot.py:160
msgid "not found, texture compass cannot be used"
msgstr "nie znaleziono, nie można użyć kompasu teksturowego"

#: ui/client_wx.py:47
msgid "Refresh"
msgstr "Odświeżać"

#: ui/client_wx.py:189
msgid "Connected"
msgstr "Połączony"

#: ui/client_wx.py:191
msgid "Disconnected"
msgstr "Niepowiązany"

#: ui/client_wx.py:218
msgid "warning, invalid choice value specified"
msgstr "ostrzeżenie, podano nieprawidłową wartość wyboru"

#: ui/scope_ui.py:24
msgid "pypilot Scope"
msgstr "Zakres pypilota"

#: ui/scope_ui.py:73
msgid "Zero"
msgstr "Zero"

#: ui/scope_ui.py:79
msgid "Scale +"
msgstr "Skala +"

#: ui/scope_ui.py:82
msgid "Scale -"
msgstr "Skala -"

#: ui/scope_ui.py:85
msgid "Offset /\\"
msgstr "Przesunięcie /\\"

#: ui/scope_ui.py:88
msgid "Offset \\/"
msgstr "Przesunięcie \\/"

#: ui/scope_ui.py:91
msgid "Freeze"
msgstr "Zamrażać"

#: ui/scope_ui.py:97
msgid "fftw"
msgstr "fftw"

#: ui/scope_ui.py:100
msgid "Time"
msgstr "Czas"

#: ui/scope_wx.py:67
msgid "values not found:"
msgstr "nie znaleziono wartości:"

#~ msgid "failed to load pilot"
#~ msgstr "nie udało się załadować pilota"

#~ msgid "in"
#~ msgstr "w"

#~ msgid "seconds"
#~ msgstr "sekundy"

#~ msgid "nmea client failed to connect to"
#~ msgstr "Klient nmea nie połączył się z"

#~ msgid "failed to create nmea socket as host:port"
#~ msgstr "nie udało się utworzyć gniazda nmea jako host:port"

#~ msgid "terminate calibration process"
#~ msgstr "zakończyć proces kalibracji"
