# Translations template for pypilot.
# Copyright (C) 2021 ORGANIZATION
# This file is distributed under the same license as the pypilot project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2021.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: pypilot 0.24\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2021-09-18 00:31-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"Generated-By: Babel 2.6.0\n"

#: pypilot/autopilot.py:139
msgid "Available Pilots"
msgstr "Доступные пилоты"

#: pypilot/autopilot.py:161
msgid "warning: failed to open special file"
msgstr "предупреждение: не удалось открыть специальный файл"

#: pypilot/autopilot.py:161
msgid "for writing"
msgstr "для записи"

#: pypilot/autopilot.py:162
msgid "cannot stroke the watchdog"
msgstr "не могу погладить сторожевого пса"

#: pypilot/autopilot.py:166
msgid "warning: failed to make autopilot process realtime"
msgstr ""
"предупреждение: не удалось сделать процесс автопилота в реальном времени"

#: pypilot/autopilot.py:337
msgid "server/client is running too _slowly_"
msgstr "сервер / клиент работает слишком медленно_"

#: pypilot/autopilot.py:343
msgid "sensors is running too _slowly_"
msgstr "датчики работают слишком медленно"

#: pypilot/autopilot.py:420
msgid "autopilot routine is running too _slowly_"
msgstr "программа автопилота работает слишком медленно"

#: pypilot/autopilot.py:429
msgid "servo is running too _slowly_"
msgstr "сервопривод работает слишком медленно"

#: pypilot/boatimu.py:33
msgid "RTIMU library not detected, please install it"
msgstr "Библиотека RTIMU не обнаружена, установите ее"

#: pypilot/boatimu.py:56
msgid "Using settings file"
msgstr "Использование файла настроек"

#: pypilot/boatimu.py:96
msgid "ERROR: No IMU Detected"
msgstr "ОШИБКА: IMU не обнаружен"

#: pypilot/boatimu.py:104
msgid "ERROR: IMU Init Failed, no inertial data available"
msgstr "ОШИБКА: сбой инициализации IMU, инерционные данные недоступны"

#: pypilot/boatimu.py:126
msgid "warning, failed to make imu process realtime"
msgstr ""
"предупреждение, не удалось заставить imu обрабатывать в реальном времени"

#: pypilot/boatimu.py:128
msgid "made imu process realtime"
msgstr "сделал imu процесс в реальном времени"

#: pypilot/boatimu.py:140
msgid "setting initial gyro bias"
msgstr "установка начального смещения гироскопа"

#: pypilot/boatimu.py:156
msgid "imu process failed to keep time"
msgstr "IMU процесс не успел вовремя"

#: pypilot/boatimu.py:164
msgid "failed to read IMU!"
msgstr "не удалось прочитать ИДУ!"

#: pypilot/boatimu.py:196
msgid "imu rate set to rate"
msgstr "imu rate установлен на рейтинг"

#: pypilot/boatimu.py:210
msgid "too high standing gyro bias, resetting sensors"
msgstr "слишком высокое смещение гироскопа, сброс датчиков"

#: pypilot/boatimu.py:215
msgid "compass out of range, resetting"
msgstr "компас вне диапазона, сброс"

#: pypilot/boatimu.py:307
msgid "warning, failed to make calibration process other"
msgstr "предупреждение, не удалось выполнить другой процесс калибровки"

#: pypilot/boatimu.py:309
msgid "warning, failed to make calibration process idle, trying renice"
msgstr ""
"предупреждение, не удалось остановить процесс калибровки, пытаюсь "
"восстановить"

#: pypilot/boatimu.py:311
msgid "warning, failed to renice calibration process"
msgstr "предупреждение, не удалось изменить процесс калибровки"

#: pypilot/boatimu.py:318
msgid "calibration loaded, starting"
msgstr "калибровка загружена, запуск"

#: pypilot/boatimu.py:322
msgid "failed import calibration fit"
msgstr "неудачная импортная калибровка"

#: pypilot/boatimu.py:439
msgid "accel values invalid"
msgstr "значения ускорения недопустимы"

#: pypilot/bufferedsocket.py:55
msgid "overflow in pypilot udp socket"
msgstr "переполнение в сокете pypilot udp"

#: pypilot/bufferedsocket.py:60
msgid "overflow in pypilot socket"
msgstr "переполнение в сокете pypilot"

#: pypilot/bufferedsocket.py:70
msgid "failed to send udp packet"
msgstr "не удалось отправить пакет UDP"

#: pypilot/bufferedsocket.py:79
msgid "pypilot socket failed to send to"
msgstr "сокету pypilot не удалось отправить"

#: pypilot/bufferedsocket.py:93
msgid "socket send took too long!?!?"
msgstr "отправка сокета заняла слишком много времени!?!?"

#: pypilot/bufferedsocket.py:95
msgid "socket send error"
msgstr "ошибка отправки сокета"

#: pypilot/bufferedsocket.py:99
msgid "pypilot socket exception"
msgstr "исключение сокета pypilot"

#: pypilot/bufferedsocket.py:103
msgid "falling back to python nonblocking socket, will consume more cpu"
msgstr "возврат к неблокирующему сокету python потребляет больше процессора"

#: pypilot/bufferedsocket.py:129
msgid "socket send error in server flush"
msgstr "ошибка отправки сокета при сбросе сервера"

#: pypilot/bufferedsocket.py:144
msgid "error receiving data"
msgstr "ошибка при получении данных"

#: pypilot/calibration_fit.py:38
msgid "failed to load scientific library, cannot perform calibration update!"
msgstr ""
"не удалось загрузить научную библиотеку, невозможно выполнить обновление "
"калибровки!"

#: pypilot/client.py:96
msgid "warning, registering existing value:"
msgstr "предупреждение, регистрация существующего значения:"

#: pypilot/client.py:157
msgid "failed to read config file:"
msgstr "не удалось прочитать файл конфигурации:"

#: pypilot/client.py:188
msgid "failed to write config file:"
msgstr "не удалось записать файл конфигурации:"

#: pypilot/client.py:190
msgid "Exception writing config file:"
msgstr "Исключение записи конфигурационного файла:"

#: pypilot/client.py:275
msgid "invalid message from server:"
msgstr "неверное сообщение от сервера:"

#: pypilot/client.py:291
msgid "warning, pypilot client aleady has connection"
msgstr "предупреждение, у клиента pypilot уже есть соединение"

#: pypilot/client.py:311
msgid "connect failed to"
msgstr "не удалось подключиться к"

#: pypilot/client.py:403
msgid "failed to connect to"
msgstr "не удалось подключиться к"

#: pypilot/client.py:460
msgid "usage"
msgstr "Применение"

#: pypilot/client.py:463
msgid "set the host or ip address"
msgstr "установить хост или IP-адрес"

#: pypilot/client.py:464
msgid "print info about each value type"
msgstr "распечатать информацию о каждом типе значения"

#: pypilot/client.py:465
msgid "continuous watch"
msgstr "непрерывное наблюдение"

#: pypilot/client.py:466
msgid "show this message"
msgstr "показать это сообщение"

#: pypilot/client.py:493
msgid "failed to retrieve value list!"
msgstr "не удалось получить список значений!"

#: pypilot/client.py:504
msgid "timeout retrieving"
msgstr "получение тайм-аута"

#: pypilot/client.py:507
msgid "missing"
msgstr "отсутствующий"

#: pypilot/failedimports.py:12
msgid ""
"pypilot failed to import required modules.  Did you forget to run sudo "
"python3 setup.py install?"
msgstr ""
"pypilot не удалось импортировать необходимые модули. Вы забыли запустить "
"sudo python3 setup.py install?"

#: pypilot/gpsd.py:45
msgid "gpsd connected"
msgstr "gpsd подключен"

#: pypilot/gpsd.py:49
msgid "gpsd failed to connect"
msgstr "gpsd не удалось подключиться"

#: pypilot/gpsd.py:55
msgid "exception connecting to gps"
msgstr "исключение при подключении к gps"

#: pypilot/gpsd.py:59
msgid "gpsd disconnected"
msgstr "gpsd отключен"

#: pypilot/gpsd.py:73
msgid "gpsd PROBE success"
msgstr "gpsd PROBE успех"

#: pypilot/gpsd.py:81
msgid "gpsd probe failed"
msgstr "зонд gpsd отказал"

#: pypilot/gpsd.py:104
msgid "gpsd deactivated"
msgstr "gpsd деактивирован"

#: pypilot/gpsd.py:137
msgid "gpsd failed to determine serial baud rate of device"
msgstr ""
"gpsd не удалось определить последовательную скорость передачи данных "
"устройства"

#: pypilot/gpsd.py:154
msgid "gpsd timeout from lack of data"
msgstr "gpsd тайм-аут из-за отсутствия данных"

#: pypilot/gpsd.py:169
msgid "gpsd received invalid message"
msgstr "gpsd получил недопустимое сообщение"

#: pypilot/gpsd.py:214
msgid "gpsd got flag for pipe:"
msgstr "gpsd получил флаг для трубы:"

#: pypilot/gpsd.py:223
msgid "gpsd serial probe"
msgstr "gpsd серийный зонд"

#: pypilot/nmea.py:86
msgid "nmea failed to parse gps"
msgstr "nmea не удалось разобрать gps"

#: pypilot/nmea.py:126
msgid "nmea failed to parse wind"
msgstr "nmea не смог разобрать ветер"

#: pypilot/nmea.py:188
msgid "exception parsing apb"
msgstr "парсинг исключений apb"

#: pypilot/nmea.py:276
msgid "unhandled nmea pipe string"
msgstr "необработанная колонна труб nmea"

#: pypilot/nmea.py:326
msgid "lost serial"
msgstr "потерянный сериал"

#: pypilot/nmea.py:349
msgid "nmea got flag for process pipe:"
msgstr "nmea получил флаг для технологической трубы:"

#: pypilot/nmea.py:370
msgid "is another process accessing it?"
msgstr "к нему обращается другой процесс?"

#: pypilot/nmea.py:372
msgid "serial device timed out"
msgstr "истекло время ожидания последовательного устройства"

#: pypilot/nmea.py:428
msgid "failed to open"
msgstr "не удалось открыть"

#: pypilot/nmea.py:484
msgid "nmea server on port"
msgstr "сервер nmea на порту"

#: pypilot/nmea.py:484
msgid "bind failed."
msgstr "привязка не удалась."

#: pypilot/nmea.py:486
msgid "listening on port"
msgstr "прослушивание порта"

#: pypilot/nmea.py:486
msgid "for nmea connections"
msgstr "для соединений nmea"

#: pypilot/nmea.py:552
msgid "nmea server has too many connections"
msgstr "Сервер nmea имеет слишком много подключений"

#: pypilot/nmea.py:578
msgid "nmea client lost connection"
msgstr "клиент nmea потерял соединение"

#: pypilot/nmea.py:583
msgid "nmea sock not in sockets!"
msgstr "nmea sock не в розетки!"

#: pypilot/nmea.py:594
msgid "nmea failed to unregister socket"
msgstr "nmea не удалось отменить регистрацию сокета"

#: pypilot/nmea.py:599
msgid "nmea failed to remove fd"
msgstr "nmea не удалось удалить fd"

#: pypilot/nmea.py:604
msgid "nmea failed to remove address"
msgstr "nmea не удалось удалить адрес"

#: pypilot/nmea.py:629
msgid "invalid value"
msgstr "Неверное значение"

#: pypilot/nmea.py:639
msgid "connect error"
msgstr "ошибка подключения"

#: pypilot/nmea.py:668 pypilot/signalk.py:239
msgid "failed to connect"
msgstr "не удалось подключиться"

#: pypilot/nmea.py:676
msgid "nmea client connected"
msgstr "клиент nmea подключен"

#: pypilot/nmea.py:705
msgid "poll took too long in nmea process!"
msgstr "опрос занял слишком много времени в процессе nmea!"

#: pypilot/nmea.py:712
msgid "nmea bridge lost server connection"
msgstr "мост nmea потерял соединение с сервером"

#: pypilot/nmea.py:715
msgid "nmea bridge lost pipe to autopilot"
msgstr "Мост Nmea потерял трубу из-за автопилота"

#: pypilot/nmea.py:738
msgid "nmea bridge unhandled poll flag"
msgstr "флаг необработанного голосования nmea bridge"

#: pypilot/nmea.py:773
msgid "nmea process loop too slow:"
msgstr "Цикл процесса nmea слишком медленный:"

#: pypilot/nonblockingpipe.py:40
msgid "error pipe block on recv!"
msgstr "ошибка блока трубы на recv!"

#: pypilot/nonblockingpipe.py:42
msgid "failed to recv nonblocking pipe!"
msgstr "не удалось восстановить неблокирующую трубу!"

#: pypilot/nonblockingpipe.py:69
msgid "pipe full"
msgstr "труба полная"

#: pypilot/nonblockingpipe.py:69
msgid "cannot send"
msgstr "не могу отправить"

#: pypilot/nonblockingpipe.py:89 pypilot/nonblockingpipe.py:145
msgid "failed to decode data socket!"
msgstr "не удалось декодировать сокет данных!"

#: pypilot/nonblockingpipe.py:103
msgid "failed to encode data socket!"
msgstr "не удалось закодировать сокет данных!"

#: pypilot/nonblockingpipe.py:155
msgid "failed write"
msgstr "не удалось написать"

#: pypilot/pyjson.py:14
msgid "WARNING: python ujson library failed, parsing will consume more cpu"
msgstr ""
"ВНИМАНИЕ: ошибка библиотеки python ujson, синтаксический анализ будет "
"потреблять больше процессора"

#: pypilot/rudder.py:117
msgid "bad rudder calibration"
msgstr "плохая калибровка руля направления"

#: pypilot/rudder.py:121
msgid "bad servo rudder calibration"
msgstr "плохая калибровка серво руля направления"

#: pypilot/rudder.py:192
msgid "servo rudder autogain failed"
msgstr "сервопривод руля направления отказал"

#: pypilot/sensors.py:41
msgid "sensor found"
msgstr "датчик найден"

#: pypilot/sensors.py:190
msgid "unknown data parsed!"
msgstr "неизвестные данные проанализированы!"

#: pypilot/serialprobe.py:30
msgid "error reading"
msgstr "чтение ошибок"

#: pypilot/serialprobe.py:86
msgid "found more devices by path"
msgstr "нашел больше устройств по пути"

#: pypilot/serialprobe.py:118
msgid "removing gps device"
msgstr "удаление устройства GPS"

#: pypilot/serialprobe.py:194
msgid "no pyudev module! will scan usb devices often!"
msgstr "нет модуля пюдев! будет часто сканировать USB-устройства!"

#: pypilot/serialprobe.py:356
msgid "success"
msgstr "успех"

#: pypilot/serialprobe.py:364
msgid "failed to record device"
msgstr "не удалось записать устройство"

#: pypilot/server.py:96
msgid "ERROR no connections in watch"
msgstr "ОШИБКА нет соединений в часах"

#: pypilot/server.py:199
msgid "remove duplicate udp connection"
msgstr "удалить повторяющееся соединение udp"

#: pypilot/server.py:340
msgid "creating config directory: "
msgstr "создание каталога конфигурации:"

#: pypilot/server.py:347 ui/boatplot.py:109
msgid "failed to load"
msgstr "ошибка загрузки"

#: pypilot/server.py:358
msgid "backup data failed as well"
msgstr "данные резервного копирования также не удалось"

#: pypilot/server.py:386
msgid "failed to write"
msgstr "не удалось написать"

#: pypilot/server.py:443
msgid "pypilot_server: bind failed; already running a server?"
msgstr "pypilot_server: сбой привязки; уже запущен сервер?"

#: pypilot/server.py:505
msgid "persistent store took too long!"
msgstr "постоянный магазин занял слишком много времени!"

#: pypilot/server.py:521
msgid "max connections reached"
msgstr "достигнуто максимальное количество подключений"

#: pypilot/server.py:524
msgid "server add socket"
msgstr "сервер добавить сокет"

#: pypilot/server.py:534
msgid "internal pipe closed, server exiting"
msgstr "внутренняя труба закрыта, сервер выходит"

#: pypilot/server.py:586
msgid "server socket closed from flush!!"
msgstr "серверный сокет закрыт из-за промывки !!"

#: pypilot/servo.py:460
msgid "servo calibration invalid"
msgstr "сервокалибровка недействительна"

#: pypilot/servo.py:589
msgid "failed to open servo on:"
msgstr "не удалось открыть сервопривод:"

#: pypilot/servo.py:596
msgid "failed set nonblocking/exclusive"
msgstr "не удалось установить неблокирующий / эксклюзивный"

#: pypilot/servo.py:627 pypilot/signalk.py:159
msgid "found"
msgstr "нашел"

#: pypilot/servo.py:749
msgid "loading servo calibration"
msgstr "загрузка серво калибровки"

#: pypilot/servo.py:753
msgid "WARNING: using default servo calibration!!"
msgstr "ВНИМАНИЕ: использование сервокалибровки по умолчанию !!"

#: pypilot/servo.py:762
msgid "probing"
msgstr "зондирование"

#: pypilot/servo.py:778
msgid "arduino servo detected"
msgstr "сервопривод Arduino обнаружен"

#: pypilot/servo.py:787
msgid "device needed for option"
msgstr "устройство, необходимое для опции"

#: pypilot/signalk.py:66
msgid "read token"
msgstr "читать токен"

#: pypilot/signalk.py:69
msgid "failed to read token"
msgstr "не удалось прочитать токен"

#: pypilot/signalk.py:76
msgid "failed to"
msgstr "не удалось"

#: pypilot/signalk.py:76
msgid "autodetection not possible"
msgstr "автоматическое обнаружение невозможно"

#: pypilot/signalk.py:77 pypilot/signalk.py:146 pypilot/signalk.py:216
msgid "try"
msgstr "пытаться"

#: pypilot/signalk.py:77 pypilot/signalk.py:146 pypilot/signalk.py:216
msgid "or"
msgstr "или же"

#: pypilot/signalk.py:108
msgid "service removed"
msgstr "служба удалена"

#: pypilot/signalk.py:112
msgid "server lost"
msgstr "сервер потерян"

#: pypilot/signalk.py:118
msgid "service add"
msgstr "добавление услуги"

#: pypilot/signalk.py:132
msgid "server found"
msgstr "найден сервер"

#: pypilot/signalk.py:141
msgid "probe"
msgstr "зонд"

#: pypilot/signalk.py:145
msgid "could not"
msgstr "не мог"

#: pypilot/signalk.py:155
msgid "failed to retrieve/parse data from"
msgstr "не удалось получить / проанализировать данные из"

#: pypilot/signalk.py:171
msgid "see if token is ready"
msgstr "посмотреть, готов ли токен"

#: pypilot/signalk.py:177
msgid "received token"
msgstr "получил токен"

#: pypilot/signalk.py:183
msgid "failed to store token"
msgstr "не удалось сохранить токен"

#: pypilot/signalk.py:187 pypilot/signalk.py:208
msgid "error requesting access"
msgstr "ошибка при запросе доступа"

#: pypilot/signalk.py:206
msgid "request access url"
msgstr "запросить URL-адрес доступа"

#: pypilot/signalk.py:215
msgid "cannot create connection:"
msgstr "не может создать соединение:"

#: pypilot/signalk.py:230
msgid "bad status, rejecting token"
msgstr "плохой статус, отклонение токена"

#: pypilot/signalk.py:234
msgid "connection refused"
msgstr "В соединении отказано"

#: pypilot/signalk.py:284
msgid "connected to"
msgstr "подключен к"

#: pypilot/signalk.py:354
msgid "Exception converting signalk->pypilot"
msgstr "Исключение преобразования сигнала-> pypilot"

#: pypilot/signalk.py:368
msgid "received"
msgstr "получили"

#: pypilot/signalk.py:414
msgid "failed to send updates"
msgstr "не удалось отправить обновления"

#: pypilot/signalk.py:428
msgid "failed to parse msg:"
msgstr "не удалось разобрать сообщение:"

#: pypilot/values.py:130
msgid "invalid initial value for range property"
msgstr "неверное начальное значение для свойства диапазона"

#: pypilot/values.py:179
msgid "invalid set"
msgstr "неверный набор"

#: pypilot/pilots/__init__.py:23
msgid "ERROR loading"
msgstr "Ошибка загрузки"

#: ui/autopilot_calibration.py:166
msgid "exception in calibration:"
msgstr "исключение при калибровке:"

#: ui/autopilot_control.py:264
msgid "warning: unhandled message"
msgstr "предупреждение: необработанное сообщение"

#: ui/autopilot_control_ui.py:24
msgid "Autopilot Control"
msgstr "Управление автопилотом"

#: ui/autopilot_control_ui.py:39
msgid "AP"
msgstr "Ты"

#: ui/autopilot_control_ui.py:57 ui/autopilot_control_ui.py:67
#: ui/autopilot_control_ui.py:460 ui/autopilot_control_ui.py:737
msgid "N/A"
msgstr "N / A"

#: ui/autopilot_control_ui.py:62
msgid "        N/A        "
msgstr "N / A"

#: ui/autopilot_control_ui.py:74
msgid "----"
msgstr "----"

#: ui/autopilot_control_ui.py:89 ui/autopilot_control_ui.py:96
msgid " N/A "
msgstr "N / A"

#: ui/autopilot_control_ui.py:121
msgid "port"
msgstr "порт"

#: ui/autopilot_control_ui.py:121
msgid "starboard"
msgstr "правый борт"

#: ui/autopilot_control_ui.py:136
msgid "Pilot"
msgstr "Пилот"

#: ui/autopilot_control_ui.py:146 ui/autopilot_control_ui.py:425
msgid "Compass"
msgstr "Компас"

#: ui/autopilot_control_ui.py:149
msgid "GPS"
msgstr "GPS"

#: ui/autopilot_control_ui.py:154
msgid "Wind"
msgstr "Ветер"

#: ui/autopilot_control_ui.py:159
msgid "True Wind"
msgstr "Настоящий ветер"

#: ui/autopilot_control_ui.py:175 ui/scope_ui.py:76
msgid "Center"
msgstr "Центр"

#: ui/autopilot_control_ui.py:199
msgid "&Scope"
msgstr "&Сфера"

#: ui/autopilot_control_ui.py:202
msgid "&Client"
msgstr "&Клиент"

#: ui/autopilot_control_ui.py:205
msgid "C&alibration"
msgstr "к&алибровка"

#: ui/autopilot_control_ui.py:208 ui/scope_ui.py:108
msgid "Close"
msgstr "Закрывать"

#: ui/autopilot_control_ui.py:304 ui/autopilot_control_ui.py:534
#: ui/autopilot_control_ui.py:654
msgid "Calibration"
msgstr "Калибровка"

#: ui/autopilot_control_ui.py:354
msgid "Boat is level"
msgstr "Лодка ровная"

#: ui/autopilot_control_ui.py:361 ui/client_wx.py:158 ui/scope_ui.py:94
msgid "Reset"
msgstr "Сброс настроек"

#: ui/autopilot_control_ui.py:382
msgid "Alignment"
msgstr "Выравнивание"

#: ui/autopilot_control_ui.py:399
msgid "Heading"
msgstr "Заголовок"

#: ui/autopilot_control_ui.py:404 ui/autopilot_control_ui.py:470
#: ui/autopilot_control_ui.py:480
msgid "     N/A     "
msgstr "N / A"

#: ui/autopilot_control_ui.py:409 ui/autopilot_control_ui.py:760
msgid "Offset"
msgstr "Компенсировать"

#: ui/autopilot_control_ui.py:423
msgid "Coords"
msgstr "Координаты"

#: ui/autopilot_control_ui.py:425
msgid "Sea"
msgstr "Море"

#: ui/autopilot_control_ui.py:425
msgid "Boat"
msgstr "Лодка"

#: ui/autopilot_control_ui.py:448 ui/client_wx.py:51
msgid "Scope"
msgstr "Сфера"

#: ui/autopilot_control_ui.py:455
msgid "Pitch"
msgstr "Подача"

#: ui/autopilot_control_ui.py:465
msgid "Roll"
msgstr "Рулон"

#: ui/autopilot_control_ui.py:475
msgid "Heel"
msgstr "Каблук"

#: ui/autopilot_control_ui.py:502
msgid "alignment"
msgstr "выравнивание"

#: ui/autopilot_control_ui.py:544 ui/autopilot_control_ui.py:664
msgid "Calibration Age"
msgstr "Возраст калибровки"

#: ui/autopilot_control_ui.py:561 ui/autopilot_control_ui.py:681
msgid "Clear"
msgstr "ясно"

#: ui/autopilot_control_ui.py:564 ui/autopilot_control_ui.py:684
msgid "calibration locked"
msgstr "калибровка заблокирована"

#: ui/autopilot_control_ui.py:587
msgid "accel"
msgstr "ускорение"

#: ui/autopilot_control_ui.py:618
msgid "Sigma Points"
msgstr "Sigma Points"

#: ui/autopilot_control_ui.py:625
msgid "local history"
msgstr "местная история"

#: ui/autopilot_control_ui.py:632
msgid "current"
msgstr "Текущий"

#: ui/autopilot_control_ui.py:639
msgid "Calibration Points"
msgstr "Точки калибровки"

#: ui/autopilot_control_ui.py:708
msgid "compass"
msgstr "компас"

#: ui/autopilot_control_ui.py:718
msgid ""
"Press each button when the rudder is at the correct position to calibrate."
msgstr ""
"Нажмите каждую кнопку, когда руль направления находится в правильном "
"положении для калибровки."

#: ui/autopilot_control_ui.py:732
msgid "Rudder"
msgstr "Руль"

#: ui/autopilot_control_ui.py:747
msgid "Reset Calibration"
msgstr "Сбросить калибровку"

#: ui/autopilot_control_ui.py:757
msgid "Rudder Is Centered"
msgstr "Руль по центру"

#: ui/autopilot_control_ui.py:765 ui/autopilot_control_ui.py:778
#: ui/autopilot_control_ui.py:791
msgid "------"
msgstr "------"

#: ui/autopilot_control_ui.py:770
msgid "Rudder is Starboard Range"
msgstr "Руль направления правого борта"

#: ui/autopilot_control_ui.py:773
msgid "Scale"
msgstr "Шкала"

#: ui/autopilot_control_ui.py:783
msgid "Rudder is Port Range"
msgstr "Руль - диапазон порта"

#: ui/autopilot_control_ui.py:786
msgid "Non Linearity"
msgstr "Нелинейность"

#: ui/autopilot_control_ui.py:803
msgid " range +-"
msgstr "диапазон + -"

#: ui/autopilot_control_ui.py:811
msgid "degrees"
msgstr "градусы"

#: ui/autopilot_control_ui.py:830
msgid "rudder"
msgstr "руль"

#: ui/autopilot_control_ui.py:832
msgid "settings"
msgstr "настройки"

#: ui/boatplot.py:25
msgid "failed to load pywavefront:"
msgstr "не удалось загрузить pywavefront:"

#: ui/boatplot.py:55
msgid "invalid display dimensions"
msgstr "неверные размеры дисплея"

#: ui/boatplot.py:110
msgid "Did you add the pypilot_data repository?"
msgstr "Вы добавили репозиторий pypilot_data?"

#: ui/boatplot.py:160
msgid "not found, texture compass cannot be used"
msgstr "не найден, текстурный компас использовать нельзя"

#: ui/client_wx.py:47
msgid "Refresh"
msgstr "Обновить"

#: ui/client_wx.py:189
msgid "Connected"
msgstr "Связанный"

#: ui/client_wx.py:191
msgid "Disconnected"
msgstr "Отключен"

#: ui/client_wx.py:218
msgid "warning, invalid choice value specified"
msgstr "предупреждение, указано недопустимое значение выбора"

#: ui/scope_ui.py:24
msgid "pypilot Scope"
msgstr "область действия pypilot"

#: ui/scope_ui.py:73
msgid "Zero"
msgstr "Нуль"

#: ui/scope_ui.py:79
msgid "Scale +"
msgstr "Масштаб +"

#: ui/scope_ui.py:82
msgid "Scale -"
msgstr "Шкала -"

#: ui/scope_ui.py:85
msgid "Offset /\\"
msgstr "Компенсировать /\\"

#: ui/scope_ui.py:88
msgid "Offset \\/"
msgstr "Компенсировать \\/"

#: ui/scope_ui.py:91
msgid "Freeze"
msgstr "Заморозить"

#: ui/scope_ui.py:97
msgid "fftw"
msgstr "fftw"

#: ui/scope_ui.py:100
msgid "Time"
msgstr "Время"

#: ui/scope_wx.py:67
msgid "values not found:"
msgstr "значения не найдены:"

#~ msgid "failed to load pilot"
#~ msgstr "не удалось загрузить пилот"

#~ msgid "in"
#~ msgstr "в"

#~ msgid "seconds"
#~ msgstr "секунды"

#~ msgid "nmea client failed to connect to"
#~ msgstr "клиенту nmea не удалось подключиться к"

#~ msgid "failed to create nmea socket as host:port"
#~ msgstr "не удалось создать сокет nmea как хост: порт"

#~ msgid "terminate calibration process"
#~ msgstr "прекратить процесс калибровки"
