# Translations template for pypilot.
# Copyright (C) 2021 ORGANIZATION
# This file is distributed under the same license as the pypilot project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2021.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: pypilot 0.24\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2021-09-18 00:31-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"Generated-By: Babel 2.6.0\n"

#: pypilot/autopilot.py:139
msgid "Available Pilots"
msgstr "Tilgængelige piloter"

#: pypilot/autopilot.py:161
msgid "warning: failed to open special file"
msgstr "advarsel: den specielle fil kunne ikke åbnes"

#: pypilot/autopilot.py:161
msgid "for writing"
msgstr "til skrivning"

#: pypilot/autopilot.py:162
msgid "cannot stroke the watchdog"
msgstr "kan ikke stryge vagthunden"

#: pypilot/autopilot.py:166
msgid "warning: failed to make autopilot process realtime"
msgstr "advarsel: kunne ikke gøre autopilot-processen realtid"

#: pypilot/autopilot.py:337
msgid "server/client is running too _slowly_"
msgstr "server / klient kører også _slowly_"

#: pypilot/autopilot.py:343
msgid "sensors is running too _slowly_"
msgstr "sensorer kører for langsomt"

#: pypilot/autopilot.py:420
msgid "autopilot routine is running too _slowly_"
msgstr "autopilotrutinen kører for langsomt"

#: pypilot/autopilot.py:429
msgid "servo is running too _slowly_"
msgstr "servo kører for langsomt"

#: pypilot/boatimu.py:33
msgid "RTIMU library not detected, please install it"
msgstr "RTIMU-biblioteket blev ikke fundet. Installer det"

#: pypilot/boatimu.py:56
msgid "Using settings file"
msgstr "Brug af indstillingsfil"

#: pypilot/boatimu.py:96
msgid "ERROR: No IMU Detected"
msgstr "FEJL: Ingen IMU fundet"

#: pypilot/boatimu.py:104
msgid "ERROR: IMU Init Failed, no inertial data available"
msgstr "FEJL: IMU-start mislykkedes, ingen inertialdata er tilgængelige"

#: pypilot/boatimu.py:126
msgid "warning, failed to make imu process realtime"
msgstr "advarsel, kunne ikke imu-processen realtid"

#: pypilot/boatimu.py:128
msgid "made imu process realtime"
msgstr "lavet imu-proces i realtid"

#: pypilot/boatimu.py:140
msgid "setting initial gyro bias"
msgstr "indstilling af indledende gyro bias"

#: pypilot/boatimu.py:156
msgid "imu process failed to keep time"
msgstr "imu-processen kunne ikke holde tiden"

#: pypilot/boatimu.py:164
msgid "failed to read IMU!"
msgstr "kunne ikke læse IMU!"

#: pypilot/boatimu.py:196
msgid "imu rate set to rate"
msgstr "imu rate indstillet til rate"

#: pypilot/boatimu.py:210
msgid "too high standing gyro bias, resetting sensors"
msgstr "for høj stående gyro bias, nulstilling af sensorer"

#: pypilot/boatimu.py:215
msgid "compass out of range, resetting"
msgstr "kompas uden for rækkevidde, nulstilling"

#: pypilot/boatimu.py:307
msgid "warning, failed to make calibration process other"
msgstr "advarsel, kalibreringsprocessen blev ikke anden"

#: pypilot/boatimu.py:309
msgid "warning, failed to make calibration process idle, trying renice"
msgstr ""
"advarsel, kunne kalibreringsprocessen ikke være inaktiv, og forsøg på at "
"forsømme"

#: pypilot/boatimu.py:311
msgid "warning, failed to renice calibration process"
msgstr "advarsel, mislykkedes kalibreringsprocessen"

#: pypilot/boatimu.py:318
msgid "calibration loaded, starting"
msgstr "kalibrering indlæst, startende"

#: pypilot/boatimu.py:322
msgid "failed import calibration fit"
msgstr "mislykket importkalibreringstilpasning"

#: pypilot/boatimu.py:439
msgid "accel values invalid"
msgstr "accel-værdier ugyldige"

#: pypilot/bufferedsocket.py:55
msgid "overflow in pypilot udp socket"
msgstr "overløb i pypilot udp-stik"

#: pypilot/bufferedsocket.py:60
msgid "overflow in pypilot socket"
msgstr "overløb i pypilotstik"

#: pypilot/bufferedsocket.py:70
msgid "failed to send udp packet"
msgstr "mislykkedes at sende udp-pakke"

#: pypilot/bufferedsocket.py:79
msgid "pypilot socket failed to send to"
msgstr "pypilot-stikket kunne ikke sendes til"

#: pypilot/bufferedsocket.py:93
msgid "socket send took too long!?!?"
msgstr "socket send tog for lang tid!?!?"

#: pypilot/bufferedsocket.py:95
msgid "socket send error"
msgstr "stikket send fejl"

#: pypilot/bufferedsocket.py:99
msgid "pypilot socket exception"
msgstr "undtagelse af pypilotstik"

#: pypilot/bufferedsocket.py:103
msgid "falling back to python nonblocking socket, will consume more cpu"
msgstr "falder tilbage til python nonblocking-sokkel, forbruger mere CPU"

#: pypilot/bufferedsocket.py:129
msgid "socket send error in server flush"
msgstr "stikket sende fejl i server skylning"

#: pypilot/bufferedsocket.py:144
msgid "error receiving data"
msgstr "fejl ved modtagelse af data"

#: pypilot/calibration_fit.py:38
msgid "failed to load scientific library, cannot perform calibration update!"
msgstr ""
"mislykkedes at indlæse videnskabeligt bibliotek, kan ikke udføre "
"kalibreringsopdatering!"

#: pypilot/client.py:96
msgid "warning, registering existing value:"
msgstr "advarsel, registrering af eksisterende værdi:"

#: pypilot/client.py:157
msgid "failed to read config file:"
msgstr "mislykkedes at læse konfigurationsfil:"

#: pypilot/client.py:188
msgid "failed to write config file:"
msgstr "mislykkedes at skrive konfigurationsfil:"

#: pypilot/client.py:190
msgid "Exception writing config file:"
msgstr "Undtagelsesskrivning konfigurationsfil:"

#: pypilot/client.py:275
msgid "invalid message from server:"
msgstr "ugyldig besked fra server:"

#: pypilot/client.py:291
msgid "warning, pypilot client aleady has connection"
msgstr "advarsel, pypilot-klienten har allerede forbindelse"

#: pypilot/client.py:311
msgid "connect failed to"
msgstr "forbindelse mislykkedes"

#: pypilot/client.py:403
msgid "failed to connect to"
msgstr "kunne ikke oprette forbindelse til"

#: pypilot/client.py:460
msgid "usage"
msgstr "brug"

#: pypilot/client.py:463
msgid "set the host or ip address"
msgstr "indstil værten eller ip-adressen"

#: pypilot/client.py:464
msgid "print info about each value type"
msgstr "udskriv info om hver værditype"

#: pypilot/client.py:465
msgid "continuous watch"
msgstr "kontinuerligt ur"

#: pypilot/client.py:466
msgid "show this message"
msgstr "vis denne besked"

#: pypilot/client.py:493
msgid "failed to retrieve value list!"
msgstr "kunne ikke hente værdilisten!"

#: pypilot/client.py:504
msgid "timeout retrieving"
msgstr "timeout hentning"

#: pypilot/client.py:507
msgid "missing"
msgstr "mangler"

#: pypilot/failedimports.py:12
msgid ""
"pypilot failed to import required modules.  Did you forget to run sudo "
"python3 setup.py install?"
msgstr ""
"pypilot kunne ikke importere krævede moduler. Glemte du at køre sudo python3 "
"setup.py installation?"

#: pypilot/gpsd.py:45
msgid "gpsd connected"
msgstr "gpsd tilsluttet"

#: pypilot/gpsd.py:49
msgid "gpsd failed to connect"
msgstr "gpsd kunne ikke oprette forbindelse"

#: pypilot/gpsd.py:55
msgid "exception connecting to gps"
msgstr "undtagelse, der forbinder til GPS"

#: pypilot/gpsd.py:59
msgid "gpsd disconnected"
msgstr "gpsd afbrudt"

#: pypilot/gpsd.py:73
msgid "gpsd PROBE success"
msgstr "gpsd PROBE succes"

#: pypilot/gpsd.py:81
msgid "gpsd probe failed"
msgstr "gpsd-probe mislykkedes"

#: pypilot/gpsd.py:104
msgid "gpsd deactivated"
msgstr "gpsd deaktiveret"

#: pypilot/gpsd.py:137
msgid "gpsd failed to determine serial baud rate of device"
msgstr "gpsd kunne ikke bestemme enhedens serielle baudrate"

#: pypilot/gpsd.py:154
msgid "gpsd timeout from lack of data"
msgstr "gpsd timeout fra mangel på data"

#: pypilot/gpsd.py:169
msgid "gpsd received invalid message"
msgstr "gpsd modtog ugyldig besked"

#: pypilot/gpsd.py:214
msgid "gpsd got flag for pipe:"
msgstr "gpsd fik flag til rør:"

#: pypilot/gpsd.py:223
msgid "gpsd serial probe"
msgstr "gpsd seriel probe"

#: pypilot/nmea.py:86
msgid "nmea failed to parse gps"
msgstr "nmea kunne ikke analysere GPS"

#: pypilot/nmea.py:126
msgid "nmea failed to parse wind"
msgstr "nmea kunne ikke analysere vind"

#: pypilot/nmea.py:188
msgid "exception parsing apb"
msgstr "undtagelse parsing apb"

#: pypilot/nmea.py:276
msgid "unhandled nmea pipe string"
msgstr "uhåndteret nmea rørstreng"

#: pypilot/nmea.py:326
msgid "lost serial"
msgstr "mistet serie"

#: pypilot/nmea.py:349
msgid "nmea got flag for process pipe:"
msgstr "nmea fik flag til procesrør:"

#: pypilot/nmea.py:370
msgid "is another process accessing it?"
msgstr "har en anden proces adgang til det?"

#: pypilot/nmea.py:372
msgid "serial device timed out"
msgstr "seriel enhed blev udløbet"

#: pypilot/nmea.py:428
msgid "failed to open"
msgstr "kunne ikke åbnes"

#: pypilot/nmea.py:484
msgid "nmea server on port"
msgstr "nmea-server på port"

#: pypilot/nmea.py:484
msgid "bind failed."
msgstr "bind mislykkedes."

#: pypilot/nmea.py:486
msgid "listening on port"
msgstr "lytter til havn"

#: pypilot/nmea.py:486
msgid "for nmea connections"
msgstr "til nmea-forbindelser"

#: pypilot/nmea.py:552
msgid "nmea server has too many connections"
msgstr "nmea server har for mange forbindelser"

#: pypilot/nmea.py:578
msgid "nmea client lost connection"
msgstr "nmea -klient mistede forbindelsen"

#: pypilot/nmea.py:583
msgid "nmea sock not in sockets!"
msgstr "nmea sok ikke i stikkontakter!"

#: pypilot/nmea.py:594
msgid "nmea failed to unregister socket"
msgstr "nmea kunne ikke afmelde stikket"

#: pypilot/nmea.py:599
msgid "nmea failed to remove fd"
msgstr "nmea kunne ikke fjerne fd"

#: pypilot/nmea.py:604
msgid "nmea failed to remove address"
msgstr "nmea kunne ikke fjerne adressen"

#: pypilot/nmea.py:629
msgid "invalid value"
msgstr "ugyldig værdi"

#: pypilot/nmea.py:639
msgid "connect error"
msgstr "forbindelsesfejl"

#: pypilot/nmea.py:668 pypilot/signalk.py:239
msgid "failed to connect"
msgstr "forbindelsen fejlede"

#: pypilot/nmea.py:676
msgid "nmea client connected"
msgstr "nmea -klient tilsluttet"

#: pypilot/nmea.py:705
msgid "poll took too long in nmea process!"
msgstr "afstemningen tog for lang tid i nmea-processen!"

#: pypilot/nmea.py:712
msgid "nmea bridge lost server connection"
msgstr "nmea bridge mistet serverforbindelse"

#: pypilot/nmea.py:715
msgid "nmea bridge lost pipe to autopilot"
msgstr "nmea bridge mistet rør til autopilot"

#: pypilot/nmea.py:738
msgid "nmea bridge unhandled poll flag"
msgstr "nmea bridge uhåndteret afstemningsflag"

#: pypilot/nmea.py:773
msgid "nmea process loop too slow:"
msgstr "nmea procesløkke for langsom:"

#: pypilot/nonblockingpipe.py:40
msgid "error pipe block on recv!"
msgstr "fejl rørblok på recv!"

#: pypilot/nonblockingpipe.py:42
msgid "failed to recv nonblocking pipe!"
msgstr "mislykkedes med at recv non-blocking pipe!"

#: pypilot/nonblockingpipe.py:69
msgid "pipe full"
msgstr "rør fuldt"

#: pypilot/nonblockingpipe.py:69
msgid "cannot send"
msgstr "kan ikke sende"

#: pypilot/nonblockingpipe.py:89 pypilot/nonblockingpipe.py:145
msgid "failed to decode data socket!"
msgstr "mislykkedes med at afkode datasocket!"

#: pypilot/nonblockingpipe.py:103
msgid "failed to encode data socket!"
msgstr "kunne ikke kode dataforbindelse!"

#: pypilot/nonblockingpipe.py:155
msgid "failed write"
msgstr "mislykket skrivning"

#: pypilot/pyjson.py:14
msgid "WARNING: python ujson library failed, parsing will consume more cpu"
msgstr ""
"ADVARSEL: python ujson-biblioteket mislykkedes, parsing bruger mere CPU"

#: pypilot/rudder.py:117
msgid "bad rudder calibration"
msgstr "dårlig rorkalibrering"

#: pypilot/rudder.py:121
msgid "bad servo rudder calibration"
msgstr "dårlig servoror kalibrering"

#: pypilot/rudder.py:192
msgid "servo rudder autogain failed"
msgstr "servoror autogain mislykkedes"

#: pypilot/sensors.py:41
msgid "sensor found"
msgstr "sensor fundet"

#: pypilot/sensors.py:190
msgid "unknown data parsed!"
msgstr "ukendte data analyseret!"

#: pypilot/serialprobe.py:30
msgid "error reading"
msgstr "fejllæsning"

#: pypilot/serialprobe.py:86
msgid "found more devices by path"
msgstr "fundet flere enheder efter sti"

#: pypilot/serialprobe.py:118
msgid "removing gps device"
msgstr "fjernelse af GPS-enhed"

#: pypilot/serialprobe.py:194
msgid "no pyudev module! will scan usb devices often!"
msgstr "intet pyudev-modul! scanner ofte usb-enheder!"

#: pypilot/serialprobe.py:356
msgid "success"
msgstr "succes"

#: pypilot/serialprobe.py:364
msgid "failed to record device"
msgstr "kunne ikke optage enhed"

#: pypilot/server.py:96
msgid "ERROR no connections in watch"
msgstr "FEJL ingen forbindelser i uret"

#: pypilot/server.py:199
msgid "remove duplicate udp connection"
msgstr "fjern dublet udp-forbindelse"

#: pypilot/server.py:340
msgid "creating config directory: "
msgstr "oprettelse af konfigurationsmappe:"

#: pypilot/server.py:347 ui/boatplot.py:109
msgid "failed to load"
msgstr "kunne ikke indlæses"

#: pypilot/server.py:358
msgid "backup data failed as well"
msgstr "sikkerhedskopieringsdata mislykkedes også"

#: pypilot/server.py:386
msgid "failed to write"
msgstr "kunne ikke skrive"

#: pypilot/server.py:443
msgid "pypilot_server: bind failed; already running a server?"
msgstr "pypilot_server: bind mislykkedes; kører du allerede en server?"

#: pypilot/server.py:505
msgid "persistent store took too long!"
msgstr "vedvarende butik tog for lang tid!"

#: pypilot/server.py:521
msgid "max connections reached"
msgstr "maks. forbindelser nået"

#: pypilot/server.py:524
msgid "server add socket"
msgstr "server tilføje stikkontakt"

#: pypilot/server.py:534
msgid "internal pipe closed, server exiting"
msgstr "internt rør lukket, server afsluttes"

#: pypilot/server.py:586
msgid "server socket closed from flush!!"
msgstr "serverstik lukket fra skyl !!"

#: pypilot/servo.py:460
msgid "servo calibration invalid"
msgstr "servokalibrering ugyldig"

#: pypilot/servo.py:589
msgid "failed to open servo on:"
msgstr "kunne ikke åbne servo på:"

#: pypilot/servo.py:596
msgid "failed set nonblocking/exclusive"
msgstr "mislykkedes sæt ikke-blokering / eksklusiv"

#: pypilot/servo.py:627 pypilot/signalk.py:159
msgid "found"
msgstr "fundet"

#: pypilot/servo.py:749
msgid "loading servo calibration"
msgstr "indlæsning af servokalibrering"

#: pypilot/servo.py:753
msgid "WARNING: using default servo calibration!!"
msgstr "ADVARSEL: Brug af standard servokalibrering !!"

#: pypilot/servo.py:762
msgid "probing"
msgstr "sondering"

#: pypilot/servo.py:778
msgid "arduino servo detected"
msgstr "arduino servo opdaget"

#: pypilot/servo.py:787
msgid "device needed for option"
msgstr "enhed, der er nødvendig til valgmulighed"

#: pypilot/signalk.py:66
msgid "read token"
msgstr "læs token"

#: pypilot/signalk.py:69
msgid "failed to read token"
msgstr "kunne ikke læse token"

#: pypilot/signalk.py:76
msgid "failed to"
msgstr "var ikke i stand til at"

#: pypilot/signalk.py:76
msgid "autodetection not possible"
msgstr "autodetektion ikke mulig"

#: pypilot/signalk.py:77 pypilot/signalk.py:146 pypilot/signalk.py:216
msgid "try"
msgstr "prøve"

#: pypilot/signalk.py:77 pypilot/signalk.py:146 pypilot/signalk.py:216
msgid "or"
msgstr "eller"

#: pypilot/signalk.py:108
msgid "service removed"
msgstr "tjeneste fjernet"

#: pypilot/signalk.py:112
msgid "server lost"
msgstr "server tabt"

#: pypilot/signalk.py:118
msgid "service add"
msgstr "service tilføj"

#: pypilot/signalk.py:132
msgid "server found"
msgstr "server fundet"

#: pypilot/signalk.py:141
msgid "probe"
msgstr "sonde"

#: pypilot/signalk.py:145
msgid "could not"
msgstr "kunne ikke"

#: pypilot/signalk.py:155
msgid "failed to retrieve/parse data from"
msgstr "kunne ikke hente / parsere data fra"

#: pypilot/signalk.py:171
msgid "see if token is ready"
msgstr "se om token er klar"

#: pypilot/signalk.py:177
msgid "received token"
msgstr "modtaget token"

#: pypilot/signalk.py:183
msgid "failed to store token"
msgstr "mislykkedes at gemme token"

#: pypilot/signalk.py:187 pypilot/signalk.py:208
msgid "error requesting access"
msgstr "fejl ved anmodning om adgang"

#: pypilot/signalk.py:206
msgid "request access url"
msgstr "anmode om adgangs -url"

#: pypilot/signalk.py:215
msgid "cannot create connection:"
msgstr "kan ikke oprette forbindelse:"

#: pypilot/signalk.py:230
msgid "bad status, rejecting token"
msgstr "dårlig status, afviser token"

#: pypilot/signalk.py:234
msgid "connection refused"
msgstr "forbindelse nægtet"

#: pypilot/signalk.py:284
msgid "connected to"
msgstr "forbundet til"

#: pypilot/signalk.py:354
msgid "Exception converting signalk->pypilot"
msgstr "Undtagelse, der konverterer skilt-> pypilot"

#: pypilot/signalk.py:368
msgid "received"
msgstr "modtaget"

#: pypilot/signalk.py:414
msgid "failed to send updates"
msgstr "kunne ikke sende opdateringer"

#: pypilot/signalk.py:428
msgid "failed to parse msg:"
msgstr "kunne ikke analysere msg:"

#: pypilot/values.py:130
msgid "invalid initial value for range property"
msgstr "ugyldig startværdi for områdeegenskab"

#: pypilot/values.py:179
msgid "invalid set"
msgstr "ugyldigt sæt"

#: pypilot/pilots/__init__.py:23
msgid "ERROR loading"
msgstr "FEJL indlæses"

#: ui/autopilot_calibration.py:166
msgid "exception in calibration:"
msgstr "undtagelse i kalibrering:"

#: ui/autopilot_control.py:264
msgid "warning: unhandled message"
msgstr "advarsel: uhåndteret besked"

#: ui/autopilot_control_ui.py:24
msgid "Autopilot Control"
msgstr "Autopilot kontrol"

#: ui/autopilot_control_ui.py:39
msgid "AP"
msgstr "Du"

#: ui/autopilot_control_ui.py:57 ui/autopilot_control_ui.py:67
#: ui/autopilot_control_ui.py:460 ui/autopilot_control_ui.py:737
msgid "N/A"
msgstr "Ikke relevant"

#: ui/autopilot_control_ui.py:62
msgid "        N/A        "
msgstr "Ikke relevant"

#: ui/autopilot_control_ui.py:74
msgid "----"
msgstr "----"

#: ui/autopilot_control_ui.py:89 ui/autopilot_control_ui.py:96
msgid " N/A "
msgstr "Ikke relevant"

#: ui/autopilot_control_ui.py:121
msgid "port"
msgstr "Havn"

#: ui/autopilot_control_ui.py:121
msgid "starboard"
msgstr "styrbord"

#: ui/autopilot_control_ui.py:136
msgid "Pilot"
msgstr "Pilot"

#: ui/autopilot_control_ui.py:146 ui/autopilot_control_ui.py:425
msgid "Compass"
msgstr "Kompas"

#: ui/autopilot_control_ui.py:149
msgid "GPS"
msgstr "GPS"

#: ui/autopilot_control_ui.py:154
msgid "Wind"
msgstr "Vind"

#: ui/autopilot_control_ui.py:159
msgid "True Wind"
msgstr "Sand vind"

#: ui/autopilot_control_ui.py:175 ui/scope_ui.py:76
msgid "Center"
msgstr "Centrum"

#: ui/autopilot_control_ui.py:199
msgid "&Scope"
msgstr "&Omfang"

#: ui/autopilot_control_ui.py:202
msgid "&Client"
msgstr "&Klient"

#: ui/autopilot_control_ui.py:205
msgid "C&alibration"
msgstr "K&alibrering"

#: ui/autopilot_control_ui.py:208 ui/scope_ui.py:108
msgid "Close"
msgstr "Tæt"

#: ui/autopilot_control_ui.py:304 ui/autopilot_control_ui.py:534
#: ui/autopilot_control_ui.py:654
msgid "Calibration"
msgstr "Kalibrering"

#: ui/autopilot_control_ui.py:354
msgid "Boat is level"
msgstr "Båden er plan"

#: ui/autopilot_control_ui.py:361 ui/client_wx.py:158 ui/scope_ui.py:94
msgid "Reset"
msgstr "Nulstil"

#: ui/autopilot_control_ui.py:382
msgid "Alignment"
msgstr "Justering"

#: ui/autopilot_control_ui.py:399
msgid "Heading"
msgstr "Overskrift"

#: ui/autopilot_control_ui.py:404 ui/autopilot_control_ui.py:470
#: ui/autopilot_control_ui.py:480
msgid "     N/A     "
msgstr "Ikke relevant"

#: ui/autopilot_control_ui.py:409 ui/autopilot_control_ui.py:760
msgid "Offset"
msgstr "Offset"

#: ui/autopilot_control_ui.py:423
msgid "Coords"
msgstr "Koordiner"

#: ui/autopilot_control_ui.py:425
msgid "Sea"
msgstr "Hav"

#: ui/autopilot_control_ui.py:425
msgid "Boat"
msgstr "Båd"

#: ui/autopilot_control_ui.py:448 ui/client_wx.py:51
msgid "Scope"
msgstr "Anvendelsesområde"

#: ui/autopilot_control_ui.py:455
msgid "Pitch"
msgstr "Tonehøjde"

#: ui/autopilot_control_ui.py:465
msgid "Roll"
msgstr "Rulle"

#: ui/autopilot_control_ui.py:475
msgid "Heel"
msgstr "Hæl"

#: ui/autopilot_control_ui.py:502
msgid "alignment"
msgstr "justering"

#: ui/autopilot_control_ui.py:544 ui/autopilot_control_ui.py:664
msgid "Calibration Age"
msgstr "Kalibreringsalder"

#: ui/autopilot_control_ui.py:561 ui/autopilot_control_ui.py:681
msgid "Clear"
msgstr "Klar"

#: ui/autopilot_control_ui.py:564 ui/autopilot_control_ui.py:684
msgid "calibration locked"
msgstr "kalibrering låst"

#: ui/autopilot_control_ui.py:587
msgid "accel"
msgstr "accelere"

#: ui/autopilot_control_ui.py:618
msgid "Sigma Points"
msgstr "Sigma Points"

#: ui/autopilot_control_ui.py:625
msgid "local history"
msgstr "lokal historie"

#: ui/autopilot_control_ui.py:632
msgid "current"
msgstr "nuværende"

#: ui/autopilot_control_ui.py:639
msgid "Calibration Points"
msgstr "Kalibreringspunkter"

#: ui/autopilot_control_ui.py:708
msgid "compass"
msgstr "kompas"

#: ui/autopilot_control_ui.py:718
msgid ""
"Press each button when the rudder is at the correct position to calibrate."
msgstr ""
"Tryk på hver knap, når roret er i den rigtige position for at kalibrere."

#: ui/autopilot_control_ui.py:732
msgid "Rudder"
msgstr "Ror"

#: ui/autopilot_control_ui.py:747
msgid "Reset Calibration"
msgstr "Nulstil kalibrering"

#: ui/autopilot_control_ui.py:757
msgid "Rudder Is Centered"
msgstr "Ror er centreret"

#: ui/autopilot_control_ui.py:765 ui/autopilot_control_ui.py:778
#: ui/autopilot_control_ui.py:791
msgid "------"
msgstr "------"

#: ui/autopilot_control_ui.py:770
msgid "Rudder is Starboard Range"
msgstr "Ror er styrbords rækkevidde"

#: ui/autopilot_control_ui.py:773
msgid "Scale"
msgstr "vægt"

#: ui/autopilot_control_ui.py:783
msgid "Rudder is Port Range"
msgstr "Ror er havneområde"

#: ui/autopilot_control_ui.py:786
msgid "Non Linearity"
msgstr "Ikke-lineæritet"

#: ui/autopilot_control_ui.py:803
msgid " range +-"
msgstr "rækkevidde + -"

#: ui/autopilot_control_ui.py:811
msgid "degrees"
msgstr "grader"

#: ui/autopilot_control_ui.py:830
msgid "rudder"
msgstr "ror"

#: ui/autopilot_control_ui.py:832
msgid "settings"
msgstr "indstillinger"

#: ui/boatplot.py:25
msgid "failed to load pywavefront:"
msgstr "mislykkedes at indlæse pywavefront:"

#: ui/boatplot.py:55
msgid "invalid display dimensions"
msgstr "ugyldige displaydimensioner"

#: ui/boatplot.py:110
msgid "Did you add the pypilot_data repository?"
msgstr "Tilføjede du pypilot_data-lageret?"

#: ui/boatplot.py:160
msgid "not found, texture compass cannot be used"
msgstr "ikke fundet, tekstur kompas kan ikke bruges"

#: ui/client_wx.py:47
msgid "Refresh"
msgstr "Opdater"

#: ui/client_wx.py:189
msgid "Connected"
msgstr "Forbundet"

#: ui/client_wx.py:191
msgid "Disconnected"
msgstr "Afbrudt"

#: ui/client_wx.py:218
msgid "warning, invalid choice value specified"
msgstr "advarsel, ugyldig valgværdi specificeret"

#: ui/scope_ui.py:24
msgid "pypilot Scope"
msgstr "pypilot Anvendelsesområde"

#: ui/scope_ui.py:73
msgid "Zero"
msgstr "Nul"

#: ui/scope_ui.py:79
msgid "Scale +"
msgstr "Skala +"

#: ui/scope_ui.py:82
msgid "Scale -"
msgstr "Vægt -"

#: ui/scope_ui.py:85
msgid "Offset /\\"
msgstr "Offset / \\"

#: ui/scope_ui.py:88
msgid "Offset \\/"
msgstr "Forskydning \\ /"

#: ui/scope_ui.py:91
msgid "Freeze"
msgstr "Fryse"

#: ui/scope_ui.py:97
msgid "fftw"
msgstr "fftw"

#: ui/scope_ui.py:100
msgid "Time"
msgstr "Tid"

#: ui/scope_wx.py:67
msgid "values not found:"
msgstr "værdier ikke fundet:"

#~ msgid "failed to load pilot"
#~ msgstr "mislykkedes at indlæse pilot"

#~ msgid "in"
#~ msgstr "i"

#~ msgid "seconds"
#~ msgstr "sekunder"

#~ msgid "nmea client failed to connect to"
#~ msgstr "nmea-klienten kunne ikke oprette forbindelse til"

#~ msgid "failed to create nmea socket as host:port"
#~ msgstr "kunne ikke oprette nmea-sokkel som vært: port"

#~ msgid "terminate calibration process"
#~ msgstr "afslut kalibreringsprocessen"
