# Translations template for pypilot.
# Copyright (C) 2021 ORGANIZATION
# This file is distributed under the same license as the pypilot project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2021.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: pypilot 0.24\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2021-09-18 00:31-0400\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"Generated-By: Babel 2.6.0\n"

#: pypilot/autopilot.py:139
msgid "Available Pilots"
msgstr "Saatavilla olevat lentäjät"

#: pypilot/autopilot.py:161
msgid "warning: failed to open special file"
msgstr "varoitus: erikoistiedoston avaaminen epäonnistui"

#: pypilot/autopilot.py:161
msgid "for writing"
msgstr "kirjoittamista varten"

#: pypilot/autopilot.py:162
msgid "cannot stroke the watchdog"
msgstr "ei voi silittää vahtikoiraa"

#: pypilot/autopilot.py:166
msgid "warning: failed to make autopilot process realtime"
msgstr "varoitus: autopilotin prosessin tekeminen reaaliaikaiseksi epäonnistui"

#: pypilot/autopilot.py:337
msgid "server/client is running too _slowly_"
msgstr "palvelin / asiakas toimii liian _hitaasti_"

#: pypilot/autopilot.py:343
msgid "sensors is running too _slowly_"
msgstr "anturit käyvät liian hitaasti"

#: pypilot/autopilot.py:420
msgid "autopilot routine is running too _slowly_"
msgstr "autopilotin rutiini toimii liian hitaasti"

#: pypilot/autopilot.py:429
msgid "servo is running too _slowly_"
msgstr "servo toimii liian hitaasti"

#: pypilot/boatimu.py:33
msgid "RTIMU library not detected, please install it"
msgstr "RTIMU-kirjastoa ei löydy, asenna se"

#: pypilot/boatimu.py:56
msgid "Using settings file"
msgstr "Asetustiedoston käyttäminen"

#: pypilot/boatimu.py:96
msgid "ERROR: No IMU Detected"
msgstr "VIRHE: IMU: ta ei havaittu"

#: pypilot/boatimu.py:104
msgid "ERROR: IMU Init Failed, no inertial data available"
msgstr "VIRHE: IMU Init epäonnistui, inertiatietoja ei ole käytettävissä"

#: pypilot/boatimu.py:126
msgid "warning, failed to make imu process realtime"
msgstr "varoitus, epäonnistui imu-prosessin tekeminen reaaliajassa"

#: pypilot/boatimu.py:128
msgid "made imu process realtime"
msgstr "teki imuprosessista reaaliaikaisen"

#: pypilot/boatimu.py:140
msgid "setting initial gyro bias"
msgstr "alkuperäisen gyro-biasin asettaminen"

#: pypilot/boatimu.py:156
msgid "imu process failed to keep time"
msgstr "imu-prosessi ei onnistunut pitämään aikaa"

#: pypilot/boatimu.py:164
msgid "failed to read IMU!"
msgstr "epäonnistui lukemaan IMU: ta!"

#: pypilot/boatimu.py:196
msgid "imu rate set to rate"
msgstr "imu-kurssi asetettu koroksi"

#: pypilot/boatimu.py:210
msgid "too high standing gyro bias, resetting sensors"
msgstr "liian korkea seisova gyro-bias, antureiden nollaaminen"

#: pypilot/boatimu.py:215
msgid "compass out of range, resetting"
msgstr "kompassi kantaman ulkopuolella, nollaus"

#: pypilot/boatimu.py:307
msgid "warning, failed to make calibration process other"
msgstr "varoitus, kalibrointiprosessia ei tehty muuksi"

#: pypilot/boatimu.py:309
msgid "warning, failed to make calibration process idle, trying renice"
msgstr "varoitus, kalibrointiprosessin siirtäminen lepotilaan epäonnistui"

#: pypilot/boatimu.py:311
msgid "warning, failed to renice calibration process"
msgstr "varoitus, kalibrointiprosessin muuttaminen epäonnistui"

#: pypilot/boatimu.py:318
msgid "calibration loaded, starting"
msgstr "kalibrointi ladattu, alkaa"

#: pypilot/boatimu.py:322
msgid "failed import calibration fit"
msgstr "epäonnistunut tuontikalibrointisovellus"

#: pypilot/boatimu.py:439
msgid "accel values invalid"
msgstr "Accel-arvot ovat virheellisiä"

#: pypilot/bufferedsocket.py:55
msgid "overflow in pypilot udp socket"
msgstr "ylivuoto pypilot udp -liitännässä"

#: pypilot/bufferedsocket.py:60
msgid "overflow in pypilot socket"
msgstr "pypilot-pistorasian ylivuoto"

#: pypilot/bufferedsocket.py:70
msgid "failed to send udp packet"
msgstr "udp-paketin lähettäminen epäonnistui"

#: pypilot/bufferedsocket.py:79
msgid "pypilot socket failed to send to"
msgstr "pypilot-pistorasian lähettäminen epäonnistui"

#: pypilot/bufferedsocket.py:93
msgid "socket send took too long!?!?"
msgstr "liittimen lähettäminen kesti liian kauan!?!?"

#: pypilot/bufferedsocket.py:95
msgid "socket send error"
msgstr "pistorasian lähetysvirhe"

#: pypilot/bufferedsocket.py:99
msgid "pypilot socket exception"
msgstr "pypilot-pistorasian poikkeus"

#: pypilot/bufferedsocket.py:103
msgid "falling back to python nonblocking socket, will consume more cpu"
msgstr ""
"palatessasi pythonin estämättömään pistorasiaan, kuluttaa enemmän prosessoria"

#: pypilot/bufferedsocket.py:129
msgid "socket send error in server flush"
msgstr "pistorasian lähetysvirhe palvelimen huuhtelussa"

#: pypilot/bufferedsocket.py:144
msgid "error receiving data"
msgstr "virhe tietojen vastaanottamisessa"

#: pypilot/calibration_fit.py:38
msgid "failed to load scientific library, cannot perform calibration update!"
msgstr ""
"tieteellisen kirjaston lataaminen epäonnistui, kalibrointipäivitystä ei voi "
"suorittaa!"

#: pypilot/client.py:96
msgid "warning, registering existing value:"
msgstr "varoitus, olemassa olevan arvon rekisteröinti:"

#: pypilot/client.py:157
msgid "failed to read config file:"
msgstr "määritystiedoston lukeminen epäonnistui:"

#: pypilot/client.py:188
msgid "failed to write config file:"
msgstr "määritystiedoston kirjoittaminen epäonnistui:"

#: pypilot/client.py:190
msgid "Exception writing config file:"
msgstr "Poikkeuksen kirjoittava määritystiedosto:"

#: pypilot/client.py:275
msgid "invalid message from server:"
msgstr "virheellinen viesti palvelimelta:"

#: pypilot/client.py:291
msgid "warning, pypilot client aleady has connection"
msgstr "varoitus, pypilot-asiakkaalla on jo yhteys"

#: pypilot/client.py:311
msgid "connect failed to"
msgstr "yhteyden muodostaminen epäonnistui"

#: pypilot/client.py:403
msgid "failed to connect to"
msgstr "yhteyden muodostaminen epäonnistui"

#: pypilot/client.py:460
msgid "usage"
msgstr "käyttö"

#: pypilot/client.py:463
msgid "set the host or ip address"
msgstr "aseta isäntä- tai ip-osoite"

#: pypilot/client.py:464
msgid "print info about each value type"
msgstr "tulosta tiedot jokaisesta arvotyypistä"

#: pypilot/client.py:465
msgid "continuous watch"
msgstr "jatkuva katselu"

#: pypilot/client.py:466
msgid "show this message"
msgstr "näytä tämä viesti"

#: pypilot/client.py:493
msgid "failed to retrieve value list!"
msgstr "arvoluettelon noutaminen epäonnistui!"

#: pypilot/client.py:504
msgid "timeout retrieving"
msgstr "aikakatkaisun haku"

#: pypilot/client.py:507
msgid "missing"
msgstr "puuttuu"

#: pypilot/failedimports.py:12
msgid ""
"pypilot failed to import required modules.  Did you forget to run sudo "
"python3 setup.py install?"
msgstr ""
"pypilot epäonnistui tarvittavien moduulien tuomisessa. Unohtuiko suorittaa "
"sudo python3 setup.py install?"

#: pypilot/gpsd.py:45
msgid "gpsd connected"
msgstr "gpsd kytketty"

#: pypilot/gpsd.py:49
msgid "gpsd failed to connect"
msgstr "gpsd-yhteyden muodostaminen epäonnistui"

#: pypilot/gpsd.py:55
msgid "exception connecting to gps"
msgstr "GPS: ään yhdistävä poikkeus"

#: pypilot/gpsd.py:59
msgid "gpsd disconnected"
msgstr "gpsd katkaistu"

#: pypilot/gpsd.py:73
msgid "gpsd PROBE success"
msgstr "gpsd PROBE menestys"

#: pypilot/gpsd.py:81
msgid "gpsd probe failed"
msgstr "GPSD-koetin epäonnistui"

#: pypilot/gpsd.py:104
msgid "gpsd deactivated"
msgstr "gpsd deaktivoitu"

#: pypilot/gpsd.py:137
msgid "gpsd failed to determine serial baud rate of device"
msgstr "gpsd ei onnistunut määrittämään laitteen sarjasiirtonopeutta"

#: pypilot/gpsd.py:154
msgid "gpsd timeout from lack of data"
msgstr "GPSD-aikakatkaisu tietojen puutteesta"

#: pypilot/gpsd.py:169
msgid "gpsd received invalid message"
msgstr "gpsd vastaanotti virheellisen viestin"

#: pypilot/gpsd.py:214
msgid "gpsd got flag for pipe:"
msgstr "gpsd sai lipun putkelle:"

#: pypilot/gpsd.py:223
msgid "gpsd serial probe"
msgstr "gpsd-sarjakoetin"

#: pypilot/nmea.py:86
msgid "nmea failed to parse gps"
msgstr "nmea ei pystynyt jäsentämään GPS: ää"

#: pypilot/nmea.py:126
msgid "nmea failed to parse wind"
msgstr "nmea ei pystynyt jäsentämään tuulta"

#: pypilot/nmea.py:188
msgid "exception parsing apb"
msgstr "poikkeus jäsentää apb"

#: pypilot/nmea.py:276
msgid "unhandled nmea pipe string"
msgstr "käsittelemätön nmea-putkijono"

#: pypilot/nmea.py:326
msgid "lost serial"
msgstr "kadonnut sarja"

#: pypilot/nmea.py:349
msgid "nmea got flag for process pipe:"
msgstr "nmea sai lipun prosessiputkelle:"

#: pypilot/nmea.py:370
msgid "is another process accessing it?"
msgstr "onko toinen prosessi pääsy siihen?"

#: pypilot/nmea.py:372
msgid "serial device timed out"
msgstr "sarjalaite aikakatkaistiin"

#: pypilot/nmea.py:428
msgid "failed to open"
msgstr "epäonnistui avaaminen"

#: pypilot/nmea.py:484
msgid "nmea server on port"
msgstr "nmea-palvelin portissa"

#: pypilot/nmea.py:484
msgid "bind failed."
msgstr "sidonta epäonnistui."

#: pypilot/nmea.py:486
msgid "listening on port"
msgstr "kuuntelee satamassa"

#: pypilot/nmea.py:486
msgid "for nmea connections"
msgstr "nmea-yhteyksille"

#: pypilot/nmea.py:552
msgid "nmea server has too many connections"
msgstr "nmea-palvelimella on liian monta yhteyttä"

#: pypilot/nmea.py:578
msgid "nmea client lost connection"
msgstr "nmea -asiakas katkaisi yhteyden"

#: pypilot/nmea.py:583
msgid "nmea sock not in sockets!"
msgstr "nmea-sukka ei ole pistorasioissa!"

#: pypilot/nmea.py:594
msgid "nmea failed to unregister socket"
msgstr "nmea ei onnistunut poistamaan pistorasian rekisteröintiä"

#: pypilot/nmea.py:599
msgid "nmea failed to remove fd"
msgstr "nmea ei onnistunut poistamaan fd: tä"

#: pypilot/nmea.py:604
msgid "nmea failed to remove address"
msgstr "nmea ei onnistunut poistamaan osoitetta"

#: pypilot/nmea.py:629
msgid "invalid value"
msgstr "Kelpaamaton arvo"

#: pypilot/nmea.py:639
msgid "connect error"
msgstr "yhteysvirhe"

#: pypilot/nmea.py:668 pypilot/signalk.py:239
msgid "failed to connect"
msgstr "ei voida yhdistää"

#: pypilot/nmea.py:676
msgid "nmea client connected"
msgstr "nmea -asiakas yhdistetty"

#: pypilot/nmea.py:705
msgid "poll took too long in nmea process!"
msgstr "kysely kesti liian kauan nmea-prosessissa!"

#: pypilot/nmea.py:712
msgid "nmea bridge lost server connection"
msgstr "nmea-silta katosi palvelinyhteyden"

#: pypilot/nmea.py:715
msgid "nmea bridge lost pipe to autopilot"
msgstr "nmea-silta menetti putken autopilotille"

#: pypilot/nmea.py:738
msgid "nmea bridge unhandled poll flag"
msgstr "nmea-silta käsittelemätön kyselylippu"

#: pypilot/nmea.py:773
msgid "nmea process loop too slow:"
msgstr "nmea-prosessisilmukka liian hidas:"

#: pypilot/nonblockingpipe.py:40
msgid "error pipe block on recv!"
msgstr "virhe putkilohko recv!"

#: pypilot/nonblockingpipe.py:42
msgid "failed to recv nonblocking pipe!"
msgstr "epäonnistui rekvisiittaista putkea!"

#: pypilot/nonblockingpipe.py:69
msgid "pipe full"
msgstr "putki täynnä"

#: pypilot/nonblockingpipe.py:69
msgid "cannot send"
msgstr "ei voi lähettää"

#: pypilot/nonblockingpipe.py:89 pypilot/nonblockingpipe.py:145
msgid "failed to decode data socket!"
msgstr "ei onnistunut purkamaan datapistoketta!"

#: pypilot/nonblockingpipe.py:103
msgid "failed to encode data socket!"
msgstr "ei onnistunut koodaamaan datapistoketta!"

#: pypilot/nonblockingpipe.py:155
msgid "failed write"
msgstr "epäonnistui kirjoittaminen"

#: pypilot/pyjson.py:14
msgid "WARNING: python ujson library failed, parsing will consume more cpu"
msgstr ""
"VAROITUS: python ujson -kirjasto epäonnistui, jäsentäminen kuluttaa enemmän "
"prosessoria"

#: pypilot/rudder.py:117
msgid "bad rudder calibration"
msgstr "huono peräsimen kalibrointi"

#: pypilot/rudder.py:121
msgid "bad servo rudder calibration"
msgstr "huono servopyörän kalibrointi"

#: pypilot/rudder.py:192
msgid "servo rudder autogain failed"
msgstr "servo-peräsimen automaattinen vahvistus epäonnistui"

#: pypilot/sensors.py:41
msgid "sensor found"
msgstr "anturi löytyi"

#: pypilot/sensors.py:190
msgid "unknown data parsed!"
msgstr "tuntemattomia tietoja on jäsennelty!"

#: pypilot/serialprobe.py:30
msgid "error reading"
msgstr "virhe luettaessa"

#: pypilot/serialprobe.py:86
msgid "found more devices by path"
msgstr "löysi lisää laitteita polun mukaan"

#: pypilot/serialprobe.py:118
msgid "removing gps device"
msgstr "GPS-laitteen poistaminen"

#: pypilot/serialprobe.py:194
msgid "no pyudev module! will scan usb devices often!"
msgstr "ei pyudev-moduulia! skannaa usb-laitteita usein!"

#: pypilot/serialprobe.py:356
msgid "success"
msgstr "menestys"

#: pypilot/serialprobe.py:364
msgid "failed to record device"
msgstr "laitteen tallennus epäonnistui"

#: pypilot/server.py:96
msgid "ERROR no connections in watch"
msgstr "VIRHE ei yhteyttä kellossa"

#: pypilot/server.py:199
msgid "remove duplicate udp connection"
msgstr "Poista päällekkäinen udp-yhteys"

#: pypilot/server.py:340
msgid "creating config directory: "
msgstr "määrityshakemiston luominen:"

#: pypilot/server.py:347 ui/boatplot.py:109
msgid "failed to load"
msgstr "lataus epäonnistui"

#: pypilot/server.py:358
msgid "backup data failed as well"
msgstr "varmuuskopiointi epäonnistui"

#: pypilot/server.py:386
msgid "failed to write"
msgstr "ei kirjoittanut"

#: pypilot/server.py:443
msgid "pypilot_server: bind failed; already running a server?"
msgstr "pypilot_server: sidonta epäonnistui; jo palvelinta?"

#: pypilot/server.py:505
msgid "persistent store took too long!"
msgstr "jatkuva myymälä kesti liian kauan!"

#: pypilot/server.py:521
msgid "max connections reached"
msgstr "maksimiliitännät saavutettu"

#: pypilot/server.py:524
msgid "server add socket"
msgstr "palvelimen lisäyspistoke"

#: pypilot/server.py:534
msgid "internal pipe closed, server exiting"
msgstr "sisäinen putki suljettu, palvelin poistuu"

#: pypilot/server.py:586
msgid "server socket closed from flush!!"
msgstr "palvelinpistoke suljettu huuhtelusta!"

#: pypilot/servo.py:460
msgid "servo calibration invalid"
msgstr "servokalibrointi on virheellinen"

#: pypilot/servo.py:589
msgid "failed to open servo on:"
msgstr "epäonnistui avaamasta servoa:"

#: pypilot/servo.py:596
msgid "failed set nonblocking/exclusive"
msgstr "epäonnistunut asetettu esto / yksinoikeus"

#: pypilot/servo.py:627 pypilot/signalk.py:159
msgid "found"
msgstr "löytyi"

#: pypilot/servo.py:749
msgid "loading servo calibration"
msgstr "servokalibroinnin lataus"

#: pypilot/servo.py:753
msgid "WARNING: using default servo calibration!!"
msgstr "VAROITUS: oletus servokalibrointi !!"

#: pypilot/servo.py:762
msgid "probing"
msgstr "koettelemalla"

#: pypilot/servo.py:778
msgid "arduino servo detected"
msgstr "arduino-servo havaittu"

#: pypilot/servo.py:787
msgid "device needed for option"
msgstr "tarvittava laite"

#: pypilot/signalk.py:66
msgid "read token"
msgstr "lukea tunnusta"

#: pypilot/signalk.py:69
msgid "failed to read token"
msgstr "tunnuksen lukeminen epäonnistui"

#: pypilot/signalk.py:76
msgid "failed to"
msgstr "epäonnistui"

#: pypilot/signalk.py:76
msgid "autodetection not possible"
msgstr "automaattinen tunnistus ei ole mahdollista"

#: pypilot/signalk.py:77 pypilot/signalk.py:146 pypilot/signalk.py:216
msgid "try"
msgstr "yrittää"

#: pypilot/signalk.py:77 pypilot/signalk.py:146 pypilot/signalk.py:216
msgid "or"
msgstr "tai"

#: pypilot/signalk.py:108
msgid "service removed"
msgstr "palvelu poistettu"

#: pypilot/signalk.py:112
msgid "server lost"
msgstr "palvelin menetetty"

#: pypilot/signalk.py:118
msgid "service add"
msgstr "palvelu lisää"

#: pypilot/signalk.py:132
msgid "server found"
msgstr "palvelin löydetty"

#: pypilot/signalk.py:141
msgid "probe"
msgstr "koetin"

#: pypilot/signalk.py:145
msgid "could not"
msgstr "ei pystynyt"

#: pypilot/signalk.py:155
msgid "failed to retrieve/parse data from"
msgstr "epäonnistui tietojen noutamisesta / jäsentämisestä"

#: pypilot/signalk.py:171
msgid "see if token is ready"
msgstr "katso onko tunniste valmis"

#: pypilot/signalk.py:177
msgid "received token"
msgstr "saanut tunnuksen"

#: pypilot/signalk.py:183
msgid "failed to store token"
msgstr "tunnuksen tallentaminen epäonnistui"

#: pypilot/signalk.py:187 pypilot/signalk.py:208
msgid "error requesting access"
msgstr "virhe pyydettäessä käyttöoikeutta"

#: pypilot/signalk.py:206
msgid "request access url"
msgstr "pyydä käyttöoikeuden URL -osoitetta"

#: pypilot/signalk.py:215
msgid "cannot create connection:"
msgstr "ei voi luoda yhteyttä:"

#: pypilot/signalk.py:230
msgid "bad status, rejecting token"
msgstr "huono tila, hylkää merkki"

#: pypilot/signalk.py:234
msgid "connection refused"
msgstr "yhteys evätty"

#: pypilot/signalk.py:284
msgid "connected to"
msgstr "yhdistetty"

#: pypilot/signalk.py:354
msgid "Exception converting signalk->pypilot"
msgstr "Poikkeus muuntaa opasteet-> pypilot"

#: pypilot/signalk.py:368
msgid "received"
msgstr "sai"

#: pypilot/signalk.py:414
msgid "failed to send updates"
msgstr "päivitysten lähettäminen epäonnistui"

#: pypilot/signalk.py:428
msgid "failed to parse msg:"
msgstr "viestin jäsennys epäonnistui:"

#: pypilot/values.py:130
msgid "invalid initial value for range property"
msgstr "alueen omaisuuden alkuarvo on virheellinen"

#: pypilot/values.py:179
msgid "invalid set"
msgstr "virheellinen sarja"

#: pypilot/pilots/__init__.py:23
msgid "ERROR loading"
msgstr "Virhe ladattaessa"

#: ui/autopilot_calibration.py:166
msgid "exception in calibration:"
msgstr "poikkeus kalibroinnissa:"

#: ui/autopilot_control.py:264
msgid "warning: unhandled message"
msgstr "varoitus: käsittelemätön viesti"

#: ui/autopilot_control_ui.py:24
msgid "Autopilot Control"
msgstr "Autopilottiohjaus"

#: ui/autopilot_control_ui.py:39
msgid "AP"
msgstr "Sinä"

#: ui/autopilot_control_ui.py:57 ui/autopilot_control_ui.py:67
#: ui/autopilot_control_ui.py:460 ui/autopilot_control_ui.py:737
msgid "N/A"
msgstr "N / A"

#: ui/autopilot_control_ui.py:62
msgid "        N/A        "
msgstr "N / A"

#: ui/autopilot_control_ui.py:74
msgid "----"
msgstr "----"

#: ui/autopilot_control_ui.py:89 ui/autopilot_control_ui.py:96
msgid " N/A "
msgstr "N / A"

#: ui/autopilot_control_ui.py:121
msgid "port"
msgstr "satamaan"

#: ui/autopilot_control_ui.py:121
msgid "starboard"
msgstr "oikealle"

#: ui/autopilot_control_ui.py:136
msgid "Pilot"
msgstr "Lentäjä"

#: ui/autopilot_control_ui.py:146 ui/autopilot_control_ui.py:425
msgid "Compass"
msgstr "Kompassi"

#: ui/autopilot_control_ui.py:149
msgid "GPS"
msgstr "GPS"

#: ui/autopilot_control_ui.py:154
msgid "Wind"
msgstr "Tuuli"

#: ui/autopilot_control_ui.py:159
msgid "True Wind"
msgstr "Todellinen tuuli"

#: ui/autopilot_control_ui.py:175 ui/scope_ui.py:76
msgid "Center"
msgstr "Keskusta"

#: ui/autopilot_control_ui.py:199
msgid "&Scope"
msgstr "&Laajuus"

#: ui/autopilot_control_ui.py:202
msgid "&Client"
msgstr "&Asiakas"

#: ui/autopilot_control_ui.py:205
msgid "C&alibration"
msgstr "&Kalibrointi"

#: ui/autopilot_control_ui.py:208 ui/scope_ui.py:108
msgid "Close"
msgstr "kiinni"

#: ui/autopilot_control_ui.py:304 ui/autopilot_control_ui.py:534
#: ui/autopilot_control_ui.py:654
msgid "Calibration"
msgstr "Kalibrointi"

#: ui/autopilot_control_ui.py:354
msgid "Boat is level"
msgstr "Vene on vaakasuorassa"

#: ui/autopilot_control_ui.py:361 ui/client_wx.py:158 ui/scope_ui.py:94
msgid "Reset"
msgstr "Nollaa"

#: ui/autopilot_control_ui.py:382
msgid "Alignment"
msgstr "Kohdistus"

#: ui/autopilot_control_ui.py:399
msgid "Heading"
msgstr "Otsikko"

#: ui/autopilot_control_ui.py:404 ui/autopilot_control_ui.py:470
#: ui/autopilot_control_ui.py:480
msgid "     N/A     "
msgstr "N / A"

#: ui/autopilot_control_ui.py:409 ui/autopilot_control_ui.py:760
msgid "Offset"
msgstr "Offset"

#: ui/autopilot_control_ui.py:423
msgid "Coords"
msgstr "Coords"

#: ui/autopilot_control_ui.py:425
msgid "Sea"
msgstr "Meri"

#: ui/autopilot_control_ui.py:425
msgid "Boat"
msgstr "Vene"

#: ui/autopilot_control_ui.py:448 ui/client_wx.py:51
msgid "Scope"
msgstr "Soveltamisala"

#: ui/autopilot_control_ui.py:455
msgid "Pitch"
msgstr "Piki"

#: ui/autopilot_control_ui.py:465
msgid "Roll"
msgstr "Rullaa"

#: ui/autopilot_control_ui.py:475
msgid "Heel"
msgstr "Kantapää"

#: ui/autopilot_control_ui.py:502
msgid "alignment"
msgstr "kohdistus"

#: ui/autopilot_control_ui.py:544 ui/autopilot_control_ui.py:664
msgid "Calibration Age"
msgstr "Kalibrointiaika"

#: ui/autopilot_control_ui.py:561 ui/autopilot_control_ui.py:681
msgid "Clear"
msgstr "Asia selvä"

#: ui/autopilot_control_ui.py:564 ui/autopilot_control_ui.py:684
msgid "calibration locked"
msgstr "kalibrointi lukittu"

#: ui/autopilot_control_ui.py:587
msgid "accel"
msgstr "Accel"

#: ui/autopilot_control_ui.py:618
msgid "Sigma Points"
msgstr "Sigma-pisteet"

#: ui/autopilot_control_ui.py:625
msgid "local history"
msgstr "paikallista historiaa"

#: ui/autopilot_control_ui.py:632
msgid "current"
msgstr "nykyinen"

#: ui/autopilot_control_ui.py:639
msgid "Calibration Points"
msgstr "Kalibrointipisteet"

#: ui/autopilot_control_ui.py:708
msgid "compass"
msgstr "kompassi"

#: ui/autopilot_control_ui.py:718
msgid ""
"Press each button when the rudder is at the correct position to calibrate."
msgstr ""
"Paina kutakin painiketta, kun peräsin on oikeassa asennossa kalibrointia "
"varten."

#: ui/autopilot_control_ui.py:732
msgid "Rudder"
msgstr "Peräsin"

#: ui/autopilot_control_ui.py:747
msgid "Reset Calibration"
msgstr "Nollaa kalibrointi"

#: ui/autopilot_control_ui.py:757
msgid "Rudder Is Centered"
msgstr "Peräsin on keskitetty"

#: ui/autopilot_control_ui.py:765 ui/autopilot_control_ui.py:778
#: ui/autopilot_control_ui.py:791
msgid "------"
msgstr "------"

#: ui/autopilot_control_ui.py:770
msgid "Rudder is Starboard Range"
msgstr "Peräsin on oikeanpuoleinen alue"

#: ui/autopilot_control_ui.py:773
msgid "Scale"
msgstr "Mittakaava"

#: ui/autopilot_control_ui.py:783
msgid "Rudder is Port Range"
msgstr "Peräsin on Port Range"

#: ui/autopilot_control_ui.py:786
msgid "Non Linearity"
msgstr "Epälineaarisuus"

#: ui/autopilot_control_ui.py:803
msgid " range +-"
msgstr "alue + -"

#: ui/autopilot_control_ui.py:811
msgid "degrees"
msgstr "astetta"

#: ui/autopilot_control_ui.py:830
msgid "rudder"
msgstr "peräsin"

#: ui/autopilot_control_ui.py:832
msgid "settings"
msgstr "asetukset"

#: ui/boatplot.py:25
msgid "failed to load pywavefront:"
msgstr "pywavefrontin lataaminen epäonnistui:"

#: ui/boatplot.py:55
msgid "invalid display dimensions"
msgstr "virheelliset näytön mitat"

#: ui/boatplot.py:110
msgid "Did you add the pypilot_data repository?"
msgstr "Lisäsitkö pypilot_data-arkiston?"

#: ui/boatplot.py:160
msgid "not found, texture compass cannot be used"
msgstr "ei löydy, tekstuurikompassia ei voida käyttää"

#: ui/client_wx.py:47
msgid "Refresh"
msgstr "virkistää"

#: ui/client_wx.py:189
msgid "Connected"
msgstr "Yhdistetty"

#: ui/client_wx.py:191
msgid "Disconnected"
msgstr "Yhteys katkaistu"

#: ui/client_wx.py:218
msgid "warning, invalid choice value specified"
msgstr "varoitus, virheellinen valinnan arvo määritetty"

#: ui/scope_ui.py:24
msgid "pypilot Scope"
msgstr "pypilot-soveltamisala"

#: ui/scope_ui.py:73
msgid "Zero"
msgstr "Nolla"

#: ui/scope_ui.py:79
msgid "Scale +"
msgstr "Skaalaa +"

#: ui/scope_ui.py:82
msgid "Scale -"
msgstr "Asteikko -"

#: ui/scope_ui.py:85
msgid "Offset /\\"
msgstr "Offset / \\"

#: ui/scope_ui.py:88
msgid "Offset \\/"
msgstr "Siirtymä \\ /"

#: ui/scope_ui.py:91
msgid "Freeze"
msgstr "Jäätykää"

#: ui/scope_ui.py:97
msgid "fftw"
msgstr "fftw"

#: ui/scope_ui.py:100
msgid "Time"
msgstr "Aika"

#: ui/scope_wx.py:67
msgid "values not found:"
msgstr "arvoja ei löydy:"

#~ msgid "failed to load pilot"
#~ msgstr "epäonnistui lataamaan pilottia"

#~ msgid "in"
#~ msgstr "sisään"

#~ msgid "seconds"
#~ msgstr "sekuntia"

#~ msgid "nmea client failed to connect to"
#~ msgstr "nmea-asiakas epäonnistui yhteyden muodostamiseen"

#~ msgid "failed to create nmea socket as host:port"
#~ msgstr "ei luonut nmea-liitäntää isäntänä: portti"

#~ msgid "terminate calibration process"
#~ msgstr "lopeta kalibrointi"
